include library.groundquests;

trigger OnAttach()
{
	if ( hasObjVar(self, "forceCrystalSpawned") )
		removeObjVar(self, "forceCrystalSpawned");

	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	if ( hasObjVar(self, "forceCrystalSpawned") )
		removeObjVar(self, "forceCrystalSpawned");

	return SCRIPT_CONTINUE;
}

messageHandler handleQuestFlavorObject()
{
	if ( !hasObjVar(self, "forceCrystalSpawned") )
	{
		string e11Carbine = "object/tangible/quest/rebel/rtp_luke_altar_force_crystal.iff";
		location here = getLocation(self);
		here.y = here.y + 0;

		obj_id objTemplate = createObject(e11Carbine, here);
		
		setObjVar(self, "forceCrystalSpawned", objTemplate);
		setObjVar(objTemplate, "objParent", self);
	}

	return SCRIPT_CONTINUE;
}

messageHandler handleQuestFlavorObjectCleanup()
{
	if ( hasObjVar(self, "forceCrystalSpawned") )
	{
		obj_id forceCrystal = getObjIdObjVar(self, "forceCrystalSpawned");
		removeObjVar(self, "forceCrystalSpawned");
		
		if ( isIdValid(forceCrystal) )
		{
			destroyObject(forceCrystal);
		}
	}
	
	return SCRIPT_CONTINUE;

}



