include library.quests;
include theme_park.tatooine.gating;
include ai.ai_combat;
	
const string QUEST_ID = gating.BIB_QUEST;
const string QUEST_SCRIPT_PATH = "theme_park.tatooine.bib_quest.";

trigger OnAttach()
{
	location hero = getLocation(self);
	hero.x = hero.x + 140;
	location squill = hero;
	setObjVar (self, "squillLoc", squill);
	quests.addQuestLocationTarget ( self, "squill", "squill", squill, 30);
	return SCRIPT_CONTINUE;
}

messageHandler IDied ()
{
	setObjVar (self, "squillKilled", 1);
	detachScript (self, "theme_park.poi.general.special.spawn_squill");
	return SCRIPT_CONTINUE;
}

trigger OnArrivedAtLocation (string name)
{
	if (name == "squill")
	{
		location squill = getLocationObjVar (self, "squillLoc");
		quests.clearQuestLocationTarget (self, "squill", "squill");
		obj_id creature = createObject ("object/creature/monster/squill/squill.iff", squill);
		attachScript (creature, "theme_park.poi.general.behavior.dangerous_animal");
		setObjVar (creature, "quester", self);	
		removeObjVar (self, "squillLoc");
		startCombat (creature, self);
		return SCRIPT_CONTINUE;
	}
	return SCRIPT_CONTINUE;
}	