include library.chat;

trigger OnAttach()
{
	messageTo(self, "barkString", null, 1, false);
	return SCRIPT_CONTINUE;
}

messageHandler barkString()
{
	if(!hasObjVar(self, "bark_string_file") || !hasObjVar(self, "bark_string_id"))
	{
		if(!hasObjVar(self, "alreadyTriedBarking"))
		{
			setObjVar(self, "alreadyTriedBarking", 1);
		}
		else
		{
		
			if(getIntObjVar(self, "alreadyTriedBarking") > 2)
				return SCRIPT_CONTINUE;

		}
		
		messageTo(self, "barkString", null, 1, false);
		return SCRIPT_CONTINUE;
	}
	
	string stringFile = getStringObjVar(self, "bark_string_file");
	if(stringFile == null || stringFile.length() <= 0)
		return SCRIPT_CONTINUE;
	
	string stringId = getStringObjVar(self, "bark_string_id");
	if(stringId == null || stringId.length() <= 0)
		return SCRIPT_CONTINUE;
	
	string_id message = new string_id(stringFile, stringId);
	chat.chat(self, message);

	return SCRIPT_CONTINUE;
}