include library.space_combat;


//------TRIGGERS---------

/*trigger OnInitialize()
{
	messageTo (self, "setupTurrets", null, 2, false);
		return SCRIPT_CONTINUE;
}*/

trigger OnAttach()
{
	messageTo (self, "setupTurrets", null, 2, false);
		return SCRIPT_CONTINUE;
}


//------MESSAGEHANDLERS---------

messageHandler setupTurrets()
{
	self = getSelf();
	string strChassisType = getShipChassisType(self);
	space_combat.setupCapitalShipFromTurretDefinition(self, strChassisType);
	return SCRIPT_CONTINUE;

}