//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SwgConversationEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_EMPTYVIEW                   101
#define IDR_MAINFRAME                   128
#define IDR_SWGCONTYPE                  129
#define IDD_BRANCHVIEW                  129
#define IDD_RESPONSEVIEW                130
#define IDB_BITMAP_SCRIPTTREEVIEW       130
#define IDR_MENU_TREEVIEW               131
#define IDD_DIALOG_TEST                 134
#define IDD_DIALOG_CHOOSE_BRANCH        135
#define IDC_EDIT_TEXT                   1004
#define IDC_EDIT_NOTES                  1005
#define IDC_BUTTON1                     1008
#define IDC_BUTTON2                     1009
#define IDC_EDIT_NPC                    1014
#define IDC_TEXT                        1014
#define IDC_BUTTON0                     1015
#define IDB_BITMAP_WARNINGVIEW          1015
#define IDC_COMBO_CONDITION             1016
#define IDC_COMBO_ACTION                1017
#define IDC_CHECK_NEGATECONDITION       1019
#define IDC_CHECK_DEBUG                 1020
#define IDC_BUTTON3                     1021
#define IDC_BUTTON4                     1022
#define IDC_COMBO_LABEL                 1025
#define IDC_COMBO_LINK                  1026
#define IDC_COMBO_PLAYERANIMATION       1027
#define IDC_COMBO_NPCANIMATION          1028
#define IDC_CHECK_USEPROSEPACKAGE       1029
#define IDC_COMBO_TOKENTO               1030
#define IDC_TEXT_VERSION                1030
#define IDC_COMBO_TOKENDI               1031
#define IDC_CHECK_GROUPECHO_RESPONSE    1031
#define IDC_COMBO_TOKENDF               1032
#define IDC_CHECK_GROUPECHO_BRANCH      1033
#define IDC_CURSOR_COPY                 1059
#define IDC_CURSOR_MOVE                 1060
#define IDR_CONVERSATIONFRAME           1232
#define IDR_SCRIPTFRAME                 1233
#define IDB_BITMAP_CONVERSATIONTREEVIEW 1234
#define ID_BUTTON_DELETE                1271
#define ID_BUTTON_DEMOTE                1272
#define ID_BUTTON_PROMOTE               1284
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDD_EDIT_FINDTEXT               8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define ID__RESPONSE_ADDBRANCH          32773
#define ID__BRANCH_ADDRESPONSE          32775
#define ID__EXPANDALL                   32777
#define ID__COLLAPSEALL                 32778
#define ID_FILE_IMPORT                  32781
#define ID__BRANCH_TEST                 32782
#define ID__SCRIPT_ADDCONDITION         32784
#define ID__SCRIPT_ADDACTION            32785
#define ID__SCRIPT_DELETE               32786
#define ID_BUTTON_COMPILE               32789
#define ID__BRANCH_DELETE               32790
#define ID__RESPONSE_DELETE             32791
#define ID__SCRIPT_RENAME               32792
#define ID_BUTTON_CONDITIONWIZARD       32802
#define ID_BUTTON_ACTIONWIZARD          32803
#define ID__SCRIPT_ADDLIBRARY           32805
#define ID_BUTTON_DELETEUNUSED          32806
#define ID__SCRIPT_DUPLICATE            32808
#define ID_APP_HELP                     32809
#define ID_BUTTON_COMPILEDEBUG          32810
#define ID_BUTTON_COMPILERELEASE        32811
#define ID_BUTTON_P4EDIT                32812
#define ID__SCRIPT_ADDLABEL             32814
#define ID_BUTTON_SCAN                  32815
#define ID_BUTTON_SPELLCHECK            32816
#define ID_BUTTON_FIND                  32818
#define ID_BUTTON_RELOADDICTIONARY      32819
#define ID_TOOLS_RELOADDICTIONARY       32820
#define ID__SCRIPT_ADDTRIGGER           32821
#define ID__SCRIPT_ADDTOKENTO           32822
#define ID__SCRIPT_ADDTOKENDI           32823
#define ID__SCRIPT_ADDTOKENDF           32824
#define ID_FILE_EXPORT                  32825
#define ID_TOOLS_GROUPECHO              32826
#define ID_GROUPECHO_FLAGALL            32827
#define ID_GROUPECHO_UNFLAGALL          32828
#define ID_GROUPECHO_UNFLAGALL32829     32829
#define ID_Menu                         32830
#define ID_BRANCH_GROUPECHO             32831
#define ID_GROUPECHO_FLAGCHILDREN       32832
#define ID_GROUPECHO_UNFLAGCHILDREN     32833
#define ID__BRANCH_GROUPECHO_FLAGCHILDREN 32834
#define ID_BRANCH_GROUPECHO_UNFLAGCHILDREN 32835
#define ID__BRANCH_GROUPECHO_UNFLAGCHILDREN 32836
#define ID__RESPONSE_GROUPECHO_FLAGCHILDREN 32837
#define ID__RESPONSE_GROUPECHO_UNFLAGCHILDREN 32838
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
