include library.ai_lib;
include library.factions;
inherits theme_park.poi.base;

trigger OnAttach ()
{
	string objective = poiGetObjective (self);
	if ( objective == "rebels")
	{
		obj_id outpost = poiCreateObject ( self, "center", "object/installation/turret/turret_block_large.iff", 0, 0 );
		factions.setFaction( outpost, factions.FACTION_REBEL );
		poiSetDestroyMessage( outpost, "outpostKilled" );

		setRebelFaction( outpost );
		obj_id tr1 = poiCreateNpc ( "reb1", "rebel", 6, 6);
		setRebelFaction( tr1 );
		obj_id tr2 = poiCreateNpc ( "reb2", "rebel", -10, 13);
		setRebelFaction( tr2 );
		obj_id tr3 = poiCreateNpc ( "reb3", "rebel", -10, 11);
		setRebelFaction( tr3 );
		obj_id tr4 = poiCreateNpc ( "reb4", "rebel", 5, 5);
		setRebelFaction( tr4 );
		obj_id tr5 = poiCreateNpc ( "reb5", "rebel", 0, -5);
		setRebelFaction( tr5 );
		obj_id tr6 = poiCreateNpc ( "reb6", "rebel", 10, 2);
		setRebelFaction( tr6 );
		factions.setFaction (outpost, "Rebel");
		attachScript (tr1, "theme_park.poi.tatooine.behavior.stormtrooper_stationary_poi");
		attachScript (tr2, "theme_park.poi.tatooine.behavior.stormtrooper_stationary_poi");
		attachScript (tr3, "theme_park.poi.tatooine.behavior.poi_waiting");
		attachScript (tr4, "theme_park.poi.tatooine.behavior.poi_waiting");

		string[] patrolPoints = new string[ 4 ];
		patrolPoints[0] = "-20, 20";
		patrolPoints[1] = "-20, -20.3";
		patrolPoints[2] = "20, 20";
		patrolPoints[3] = "20, -20";
		ai_lib.setPatrolPath (tr5, patrolPoints);
		string[] patrolPoints2 = new string[ 5 ];
		patrolPoints2[0] = "15, 15";
		patrolPoints2[1] = "15, -15.3";
		patrolPoints2[2] = "-15, -15";
		patrolPoints2[3] = "-15, 15";
		patrolPoints2[4] = "-20, 20";
		ai_lib.setPatrolPath (tr6, patrolPoints2);
	}
	return SCRIPT_CONTINUE;
}

void setRebelFaction( obj_id target )
{
	factions.setFaction( target, "Rebel");
}

messageHandler outpostKilled()
{
	poiComplete( POI_SUCCESS );
	return SCRIPT_CONTINUE;
}
