include library.hue;
include library.colors;
include library.ai_lib;
include library.factions;
include ai.ai;


trigger OnInitialize()
{
	return SCRIPT_CONTINUE;
}


trigger OnAttach()
{
	if (!hasObjVar (self, "dressed"));
	{
		obj_id suit = createObject ("object/tangible/wearables/bodysuit/bodysuit_tie_fighter.iff", self, "");
		obj_id boots = createObject ("object/tangible/wearables/boots/boots_s03.iff", self, "");
		hue.hueObject (self);
		pvpSetAlignedFaction (self, ##"imperial");
		pvpMakeDeclared(self);
		string hair_table = "datatables/npc_customization/human_male_hair.iff";
		int numHair = dataTableGetNumRows (hair_table);
		int hairCol = dataTableGetNumColumns (hair_table);
		hairCol = hairCol - 1;
		numHair = numHair - 1;
		hairCol = rand (1, hairCol);
		numHair = rand (1, numHair);
		string hair = dataTableGetString ( hair_table, numHair, hairCol );
		obj_id hairStyle = createObject (hair, self, "");
		hue.hueObject (hairStyle);
		setObjVar (self, "dressed", 1);
	}
	return SCRIPT_CONTINUE;
}


trigger OnDestroy ()
{
	obj_id club = getObjIdObjVar( self, "club" );
	messageTo( club, "pilot1Died", null, 20, true );
	return SCRIPT_CONTINUE;
}
