include library.utils;



trigger OnInitialize()

{

            messageTo (self, "setUp", null, 2, false);

            return SCRIPT_CONTINUE;

}





messageHandler setUp ()

{

            string[] needs = new string[4];




            needs[0]= "object/tangible/loot/simple_kit/legacy_droid_body.iff";

            needs[1] = "object/tangible/loot/simple_kit/legacy_droid_inners.iff";

            needs[2] = "object/tangible/loot/simple_kit/legacy_droid_legs.iff";

            needs[3] = "object/tangible/loot/simple_kit/legacy_droid_motivator.iff";




            setObjVar (self, "needs", needs);

            setObjVar (self, "overview", needs);



            setObjVar (self, "reward", "object/tangible/loot/simple_kit/legacy_droid_dead.iff");

            return SCRIPT_CONTINUE;

}
