include library.utils;
include library.factions;
include library.buff;

const string[] RESTRICTED_BUFFS = {	"invis_forceCloak", "cover", "paralyze", "paralyze_1", "stasis", "feign_death"};

trigger OnAttach()
{

	messageTo(self, "setStandbyMode", null, 1, false);
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	obj_id mom = getObjIdObjVar(self, "event_perk.mom");
	int gameState = utils.getIntScriptVar(mom, "event_perk.game_state");

	int playerFactionId = pvpGetAlignedFaction(player);
	string playerFaction = factions.getFactionNameByHashCode(playerFactionId);

	obj_id ownerId = getObjIdObjVar(self, "event_perk.owner");
	if(player == ownerId && (gameState == 0 || gameState == 4) ) // Not started yet.
	{

		int menu = mi.addRootMenu(menu_info_types.SERVER_MENU1, new string_id("event_perk", "flag_game_set_time_root"));

		mi.addSubMenu(menu, menu_info_types.SERVER_MENU2, new string_id("event_perk", "flag_game_set_time_10"));
		mi.addSubMenu(menu, menu_info_types.SERVER_MENU3, new string_id("event_perk", "flag_game_set_time_20"));
		mi.addSubMenu(menu, menu_info_types.SERVER_MENU4, new string_id("event_perk", "flag_game_set_time_30"));
		mi.addSubMenu(menu, menu_info_types.SERVER_MENU6, new string_id("event_perk", "flag_game_set_time_60"));
		mi.addSubMenu(menu, menu_info_types.SERVER_MENU7, new string_id("event_perk", "flag_game_start"));

		int menu2 = mi.addRootMenu(menu_info_types.SERVER_MENU9, new string_id("event_perk", "flag_game_show_scores")); // added
		int menu10 = mi.addRootMenu(menu_info_types.SERVER_MENU10, new string_id("event_perk", "mnu_redeed"));
		int menu5 = mi.addRootMenu(menu_info_types.SERVER_MENU5, new string_id("event_perk", "mnu_show_exp_time"));
		
		return SCRIPT_CONTINUE;
	}

	if( (gameState > 0 && gameState < 4) && canUseMe(player, self))	// Game is on
	{
		int menu = mi.addRootMenu(menu_info_types.SERVER_MENU8, new string_id("event_perk", "flag_game_capture_flag"));
		return SCRIPT_CONTINUE;
	}

	if(gameState == 4 && canUseMe(player, self) )	// Game over state
	{
		int menu = mi.addRootMenu(menu_info_types.SERVER_MENU9, new string_id("event_perk", "flag_game_show_scores"));
		return SCRIPT_CONTINUE;
	}
	
	return SCRIPT_CONTINUE;


}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	dictionary params = new dictionary();
	obj_id mom = getObjIdObjVar(self, "event_perk.mom");

	if(item == menu_info_types.SERVER_MENU2)
	{
		params.put("timeLimit", 40);	//40 15 second pulses OMG
		messageTo(mom, "setTimeLimit", params, 1, false);
		sendSystemMessage(player, new string_id("event_perk", "flag_game_set_time_10"));
	}

	if(item == menu_info_types.SERVER_MENU3)
	{
		params.put("timeLimit", 80);
		messageTo(mom, "setTimeLimit", params, 1, false);
		sendSystemMessage(player, new string_id("event_perk", "flag_game_set_time_20"));
	}
	
	if(item == menu_info_types.SERVER_MENU4)
	{
		params.put("timeLimit", 120);
		messageTo(mom, "setTimeLimit", params, 1, false);
		sendSystemMessage(player, new string_id("event_perk", "flag_game_set_time_30"));
	}

	if(item == menu_info_types.SERVER_MENU6)
	{
		params.put("timeLimit", 240);
		messageTo(mom, "setTimeLimit", params, 1, false);
		sendSystemMessage(player, new string_id("event_perk", "flag_game_set_time_60"));
	}

	if(item == menu_info_types.SERVER_MENU7)
	{
		messageTo(mom, "startGame", null, 1, false);
	}

	if(item == menu_info_types.SERVER_MENU8  && canUseMe(player, self))
	{
		params.put("player", player);
		messageTo(mom, "tryToSwapFlags", params, 1, false);
	}

	if(item == menu_info_types.SERVER_MENU9)
	{
		params.put("player", player);
		messageTo(mom, "showScores", params, 1, false);
	}

	if(item == menu_info_types.SERVER_MENU10)
	{
		params.put("player", player);
		messageTo(mom, "tryRedeeding", params, 1, false);
	}

	if(item == menu_info_types.SERVER_MENU5)
	{
		params.put("player", player);
		messageTo(mom, "showTimeTillExpiration", params, 1, false);
	}
	
	return SCRIPT_CONTINUE;
}

messageHandler setStandbyMode()
{
	int gameState = 0;
	utils.setScriptVar(self, "event_perk.game_state", gameState);	


	return SCRIPT_CONTINUE;
}

messageHandler goDie()
{
	destroyObject(self);
	return SCRIPT_CONTINUE;
}

boolean canUseMe(obj_id player, obj_id self)
{
	string ownerName = getStringObjVar(self, "event_perk.owner_name");
	float playerTerminalRegistration = getFloatObjVar(player, "event_perk.terminal_registration");
	float myTerminalRegistration = getFloatObjVar(self, "event_perk.terminal_registration");
	int gameState = utils.getIntScriptVar(self, "event_perk.game_state");
	int playerFactionId = pvpGetAlignedFaction(player);
	string playerFaction = factions.getFactionNameByHashCode(playerFactionId);
	int pvpType = pvpGetType(player);

	for(int i = 0; i < RESTRICTED_BUFFS.length; i++)
	{
		if(buff.hasBuff(player, RESTRICTED_BUFFS[i]) )
		{
			return false;
		}
	}

	if(pvpType == PVPTYPE_DECLARED)
	{		
		if( (gameState == 2 && playerFaction.equals("Imperial")) || (gameState == 3 && playerFaction.equals("Rebel")) )
			return false;
		else
			return true;
	}


	return false;
}