include library.create;
include library.ai_lib;


trigger OnInitialize()
{

	string spawn = getStringObjVar (self, "spawns");
	obj_id celeb = create.object(spawn, getLocation(self));
	setInvulnerable(celeb, true);
	ai_lib.setDefaultCalmBehavior( celeb, ai_lib.BEHAVIOR_SENTINEL );
	ai_lib.setMood(celeb, "calm");

	if (hasObjVar (self, "quest_script"))
	{
		string script = getStringObjVar (self, "quest_script");
		attachScript (celeb, script);
	}

	if (hasObjVar (self, "npc_name"))
	{
		string name = getStringObjVar (self, "npc_name");
		
		if (name != null)
		{
			if (name != "")
			{
				setName (celeb, name);
			}
		}			
	}		

	string myType = getStringObjVar(self, "promoter_type");
	setObjVar(celeb, "event_perk.promoter.promoter_type", myType);

	return SCRIPT_CONTINUE;
}