include library.create;
include library.locations;

trigger OnInitialize()
{

	if(!hasObjVar(self, "event_perk.promoter"))
	{
		location here = getLocation(self);
		string myPlanet = getCurrentSceneName();	
		string myCity = locations.getCityName(here);
	

		obj_id spawnCell = getCellId(self, "r10");
		location spawnPoint = getLocation(self);
		spawnPoint.x = -23.0f;
		spawnPoint.y = 1.6f;
		spawnPoint.z = -15.0f;
		spawnPoint.cell = spawnCell;

		if(!isIdValid(spawnCell) )
		{
			return SCRIPT_CONTINUE;
		}

		obj_id template = create.object("object/tangible/spawning/static_npc/event_promoter_neutral.iff", spawnPoint);
		setObjVar(self, "event_perk.promoter", template);
		return SCRIPT_CONTINUE;

/******** All promoters are neutral and spawn everywhere now so we don't need this.

		if(!myPlanet.equals("tatooine") && !myPlanet.equals("corellia") && !myPlanet.equals("naboo") )
			return SCRIPT_CONTINUE;

		if(myCity.equals("bestine") || myCity.equals("theed") || myCity.equals("kor_vella") )	// Imp
		{
			obj_id template = create.object("object/tangible/spawning/static_npc/event_promoter_imp.iff", spawnPoint);
			setObjVar(self, "event_perk.promoter", template);
			return SCRIPT_CONTINUE;
		}

		if(myCity.equals("mos_entha") || myCity.equals("keren") || myCity.equals("doaba_guerfel") )	// Neutrals
		{
			obj_id template = create.object("object/tangible/spawning/static_npc/event_promoter_neutral.iff", spawnPoint);
			setObjVar(self, "event_perk.promoter", template);
			return SCRIPT_CONTINUE;
		}

		if(myCity.equals("mos_espa") || myCity.equals("moenia") || myCity.equals("coronet") )	// Rebels	
		{
			obj_id template = create.object("object/tangible/spawning/static_npc/event_promoter_reb.iff", spawnPoint);
			setObjVar(self, "event_perk.promoter", template);
			return SCRIPT_CONTINUE;
		}
********************************************/
	}

	return SCRIPT_CONTINUE;
}