<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(Platform)' == 'x64'">
    <OutDir>$(MSBuildThisFileDirectory)src\build\win32\x64\$(Configuration)\</OutDir>
    <IntDir>$(OutDir)obj\$(MSBuildProjectName)\</IntDir>
    <SwgOutputSuffix Condition="'$(Configuration)' == 'Release'">r</SwgOutputSuffix>
    <SwgOutputSuffix Condition="'$(Configuration)' == 'Optimized'">o</SwgOutputSuffix>
    <SwgOutputSuffix Condition="'$(Configuration)' == 'Debug'">d</SwgOutputSuffix>
    <TargetName Condition="'$(MSBuildProjectName)' == 'SwgClient'">SwgClient_$(SwgOutputSuffix)</TargetName>
    <TargetName Condition="'$(MSBuildProjectName)' == 'Direct3d9'">gl05_$(SwgOutputSuffix)</TargetName>
    <TargetName Condition="'$(MSBuildProjectName)' == 'Direct3d9_ffp'">gl06_$(SwgOutputSuffix)</TargetName>
    <TargetName Condition="'$(MSBuildProjectName)' == 'Direct3d9_vsps'">gl07_$(SwgOutputSuffix)</TargetName>
    <TargetName Condition="'$(MSBuildProjectName)' == 'Direct3d11'">gl11_$(SwgOutputSuffix)</TargetName>
  </PropertyGroup>

  <ItemDefinitionGroup Condition="'$(Platform)' == 'x64'">
    <ClCompile>
      <AssemblerListingLocation>$(IntDir)</AssemblerListingLocation>
      <ObjectFileName>$(IntDir)</ObjectFileName>
      <PrecompiledHeaderOutputFile>$(IntDir)$(MSBuildProjectName).pch</PrecompiledHeaderOutputFile>
      <ProgramDataBaseFileName>$(IntDir)$(MSBuildProjectName).pdb</ProgramDataBaseFileName>
    </ClCompile>
    <ResourceCompile>
      <ResourceOutputFileName>$(IntDir)%(Filename).res</ResourceOutputFileName>
    </ResourceCompile>
    <Bscmake>
      <OutputFile>$(IntDir)$(MSBuildProjectName).bsc</OutputFile>
    </Bscmake>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(Platform)' == 'x64' and '$(ConfigurationType)' == 'StaticLibrary'">
    <Lib>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
    </Lib>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(Platform)' == 'x64' and '$(ConfigurationType)' == 'DynamicLibrary'">
    <Link>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
      <ImportLibrary>$(OutDir)$(TargetName).lib</ImportLibrary>
      <ProgramDatabaseFile>$(OutDir)$(TargetName).pdb</ProgramDatabaseFile>
    </Link>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup Condition="'$(Platform)' == 'x64' and '$(ConfigurationType)' == 'Application'">
    <Link>
      <OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>
      <ProgramDatabaseFile>$(OutDir)$(TargetName).pdb</ProgramDatabaseFile>
    </Link>
  </ItemDefinitionGroup>
</Project>
