include library.ai_lib;
include library.hue;
include library.colors;

const string CONVO = "celebrity/charal";

trigger OnAttach ()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );

//	setObjVar (self, "quest_table", "charal");
//	attachScript (self, "npc.static_quest.quest_convo");
	detachScript (self, "npc.converse.npc_converse_menu");
	setInvulnerable (self, true);

//	debugSpeakMsg (self, "The Night Sister.");
	return SCRIPT_CONTINUE;
}
