include library.create;
include library.ai_lib;


trigger OnInitialize()
{
	string setting = getConfigSetting("EventTeam", "empireDay");

	if(setting == null || setting == "")
		return SCRIPT_CONTINUE;

	if (setting == "true" || setting == "1")
	{
		string spawn = getStringObjVar (self, "spawns");
		obj_id celeb = create.object (spawn, getLocation(self));
		setObjVar(self, "celeb", celeb);

		if(!isIdValid(celeb) )
			return SCRIPT_CONTINUE;

		setInvulnerable(celeb, true);
		ai_lib.setDefaultCalmBehavior( celeb, ai_lib.BEHAVIOR_SENTINEL );

		messageTo(self, "postSpawnScriptDetach", null, 30, false);
	
		if (hasObjVar (self, "quest_script"))
		{
			string script = getStringObjVar (self, "quest_script");
			attachScript (celeb, script);
		}
		if (hasObjVar (self, "quest_table"))
		{
			string table = getStringObjVar (self, "quest_table");
			setObjVar (celeb, "quest_table", table);
		}	
	
		if (hasObjVar (self, "npc_name"))
		{
			string name = getStringObjVar (self, "npc_name");
			
			if (name != null)
			{
				if (name != "")
				{
					setName (celeb, name);
				}
			}			
		}		
	}
	else
		return SCRIPT_OVERRIDE;
		
	return SCRIPT_CONTINUE;
}

messageHandler postSpawnScriptDetach()
{
	obj_id celeb = getObjIdObjVar(self, "celeb");

	if(hasScript(celeb, "npc.faction_recruiter.recruiter_setup") )
		detachScript(celeb, "npc.faction_recruiter.recruiter_setup");

	if(hasScript(celeb, "npc.faction_recruiter.faction_recruiter") )
		detachScript(celeb, "npc.faction_recruiter.faction_recruiter");

	if(hasScript(celeb, "conversation.faction_recruiter_imperial") )
		detachScript(celeb, "conversation.faction_recruiter_imperial");

	if(hasScript(celeb, "conversation.faction_recruiter_rebel") )
		detachScript(celeb, "conversation.faction_recruiter_rebel");

	if(hasScript(celeb, "theme_park.imperial.quest_convo") )
		detachScript(celeb, "theme_park.imperial.quest_convo");

	if(hasScript(celeb, "npc.celebrity.han_solo") )
		detachScript(celeb, "npc.celebrity.han_solo");

	if(hasScript(celeb, "theme_park.rebel.quest_convo") )
		detachScript(celeb, "theme_park.rebel.quest_convo");

	return SCRIPT_CONTINUE;
}