include library.ai_lib;
include library.chat;
include library.factions;
include library.skill;

const string CONVO = "celebrity/lady_valarian";

trigger OnInitialize()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	detachScript (self, "npc.celebrity.lady_valarian");
	return SCRIPT_CONTINUE;
}


trigger OnAttach()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	detachScript (self, "npc.celebrity.lady_valarian");
	return SCRIPT_CONTINUE;
}
