include library.ai_lib;

trigger OnAttach()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	debugSpeakMsg (self, "Aren't you a little short for a stormtrooper?");
	

	messageTo(self, "handleAttachConvoScript", null, 1, false);
	//setObjVar (self, "quest_table", "leia" );
	//setObjVar (self, "minGating", 13);
	//setObjVar (self, "maxGating", 18);
	
	return SCRIPT_CONTINUE;
}

messageHandler handleAttachConvoScript()
{
	if ( getCreatureName(self).equals("leia_organa") )
	{
		attachScript (self, "conversation.rtp_leia_main");
	}
	return SCRIPT_CONTINUE;
}

