include library.ai_lib;
include library.hue;
include library.colors;
include library.chat;
include library.factions;
include library.skill;

trigger OnAttach()
{
	setName( self, "Inquisitor Loam Redge");
	pvpSetAlignedFaction (self, ##"imperial");
	pvpMakeDeclared(self);
	
	//obj_id hair = createObject ("object/tangible/hair/human/hair_human_male_s02.iff", self, "");
	//obj_id robe =  createObject ("object/tangible/wearables/robe/robe_s12.iff", self, "");
	//obj_id shoes = createObject ("object/tangible/wearables/shoes/shoes_s01.iff", self, "");

	//hue.setColor (hair, 0, colors.GREY);
	//hue.setColor (shoes, 1, colors.BLACK);
	
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	
	//setObjVar (self, "quest_table", "loam_redge");
	//setObjVar (self, "minGating", 5);
	//setObjVar (self, "maxGating", 9);
	
	attachScript (self, "conversation.itp_loam_main");
	
	return SCRIPT_CONTINUE;
}