include library.ai_lib;

//const string CONVO = "celebrity/luke_skywalker";

trigger OnAttach ()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	debugSpeakMsg (self, "Aw...");
	
	attachScript (self, "conversation.rtp_luke_main");
	//setObjVar (self, "quest_table", "luke_skywalker" );
	//setObjVar (self, "minGating", 43);
	//setObjVar (self, "maxGating", 48);
	
	return SCRIPT_CONTINUE;
}	
