include library.factions;
include library.ai_lib;
include library.chat;
include library.skill;

trigger OnAttach()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	if (!hasScript (self, "npc.converse.npc_converse_menu"))
	{
		attachScript (self, "npc.converse.npc_converse_menu");
	}
	
	if (!hasScript (self, "npc.static_quest.quest_convo"))
	{
		attachScript (self, "npc.static_quest.quest_convo");
	}
	
	setObjVar (self, "quest_table", "prefect_talmont");
	factions.setFaction (self, "Imperial");
	return SCRIPT_CONTINUE;
}	

trigger OnInitialize()
{
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	if (!hasScript (self, "npc.converse.npc_converse_menu"))
	{
		attachScript (self, "npc.converse.npc_converse_menu");
	}
	
	if (!hasScript (self, "npc.static_quest.quest_convo"))
	{
		attachScript (self, "npc.static_quest.quest_convo");
	}
	
	setObjVar (self, "quest_table", "prefect_talmont");
	factions.setFaction (self, "Imperial");
	return SCRIPT_CONTINUE;
}	

