// ======================================================================
//
// space.load_test.load_test_player
//
// Copyright 2004 Sony Online Entertainment
//
// ======================================================================

include library.load_test;
include library.utils;

// ======================================================================

trigger OnRemovingFromWorld()
{
	destroyAiShips(self);
	return SCRIPT_CONTINUE;
}

// ----------------------------------------------------------------------

void destroyAiShips(obj_id self)
{
	dictionary d = self.getScriptDictionary();
	if (d != null)
	{
		obj_id[] aiShips = d.getObjIdArray(load_test.VAR_AI_SHIPS);
		if (aiShips != null)
		{
			for (int i = 0; i < aiShips.length; ++i)
				if (isIdValid(aiShips[i]) && aiShips[i].isLoaded())
					destroyObject(aiShips[i]);
			d.remove(load_test.VAR_AI_SHIPS);
		}
	}
}

// ======================================================================

