// ======================================================================
//
// space.load_test.load_test_ai.script
//
// Copyright 2004 Sony Online Entertainment
//
// ======================================================================

include library.ship_ai;
include library.utils;

// ======================================================================

const float PING_TIME = 120.0f;

// ======================================================================

trigger OnAttach()
{
	obj_id followTarget = utils.getObjIdScriptVar(self, "followTarget");
	if (isIdValid(followTarget))
		ship_ai.spaceFollow(self, followTarget, 15.f);
	
	messageTo(self, "ping", null, 0, false);
	return SCRIPT_CONTINUE;
}

// ----------------------------------------------------------------------

messageHandler ping()
{
	obj_id followTarget = utils.getObjIdScriptVar(self, "followTarget");
	if (!isIdValid(followTarget) || !followTarget.isLoaded())
		destroyObject(self);
	else
		messageTo(self, "ping", null, PING_TIME, false);
	return SCRIPT_CONTINUE;
}

// ======================================================================

