include ai.ai_combat;
inherits theme_park.poi.base;

trigger OnAttach ()
{
	debugSpeakMsg (self, "First POI Test Attached");
	return SCRIPT_CONTINUE;
}

trigger OnInitialize ()
{
	string objective = poiGetObjective (self);
	if ( objective == "troopers")
	{
		debugSpeakMsg (self, "In Oninitialize");
		obj_id rancor = poiCreateObject (self, "rancor", "object/creature/monster/rancor/rancor.iff", 0, 0);
		obj_id st1 = poiCreateNpc ("stormtrooper", 7, 5);
		obj_id st2 = poiCreateNpc ("stormtrooper", 5, 5);
		obj_id st3 = poiCreateNpc ("stormtrooper", 7, 7);
		obj_id st4 = poiCreateNpc ("stormtrooper", 5, 7);
		dictionary parms = new dictionary();
		parms.put( "rancor", rancor);
		messageTo (self, "attackRancor", parms, 10, true);
		return SCRIPT_CONTINUE;
	}
return SCRIPT_CONTINUE;
}

messageHandler attackRancor()
{
	
	obj_id rancor = params.getObjId ("rancor");
	startCombat (self, rancor);
	return SCRIPT_CONTINUE;
}	

