
//------------------------------------------------
// Includes
//------------------------------------------------

include library.bio_engineer;

//------------------------------------------------
// Constants
//------------------------------------------------


//------------------------------------------------
// Trigger & Message Handlers
//------------------------------------------------


trigger OnObjectMenuRequest (obj_id player, menu_info mi)
{
	//check player skill/commands here
	if (getSkillStatMod (player, "dna_harvesting") > 0)
	{
		int subHarvestDNA = mi.addRootMenu (menu_info_types.SERVER_HARVEST_CORPSE, bio_engineer.SID_HARVEST_DNA);
	}

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect (obj_id player, int item)
{
	if (item == menu_info_types.SERVER_HARVEST_CORPSE)
	{
		if (getSkillStatMod(player, "dna_harvesting") > 0)
		{
			queueCommand (player, ##"harvestDNA", self, "", COMMAND_PRIORITY_DEFAULT);
			return SCRIPT_CONTINUE;
		}
	}

	return SCRIPT_CONTINUE;
}


