include library.chat;
include library.utils;
include library.ai_lib;	

const string CONVO = "epic_quest/zicx_bug_bomb/rori_goru_rainstealer";

trigger OnAttach()
{
	attachScript (self, "npc.converse.npc_converse_menu");
	ai_lib.setDefaultCalmBehavior ( self, ai_lib.BEHAVIOR_SENTINEL );
	setInvulnerable(self, true);
	return SCRIPT_CONTINUE;
}

trigger OnStartNpcConversation (obj_id speaker)
{
	if (!hasObjVar (speaker, "zicx"))
	{
		string npcGreet = "OMG_Dont_kill_me";
		string response1 = "what_thugs" ;
		string response2 = "make_me_a_bomb";
		string response3 = "just_passing";
		
		string_id greeting = new string_id (CONVO,npcGreet);
		
		string_id response[] = new string_id [3];
		response[0] = new string_id (CONVO, response1);
		response[1] = new string_id (CONVO, response2);
		response[2] = new string_id (CONVO, response3);
		
		npcStartConversation (speaker, self, "questConvo", greeting, response);
	}
	else
	{
		string zicx = getStringObjVar (speaker, "zicx");

		if (zicx == "reset")
		{
			string npcGreet = "change_your_mind";
			string response1 = "yes_please" ;
			string response2 = "no_thanks" ;

			string_id greeting = new string_id (CONVO,npcGreet);

			string_id response[] = new string_id [2];
			response[0] = new string_id (CONVO, response1);
			response[1] = new string_id (CONVO, response2);
			npcStartConversation (speaker, self, "questConvo", greeting, response);
		}

		if (zicx == "start")
		{
			string npcGreet = "are_you_done";
			string response1 = "need_more_time" ;
			string response2 = "i_quit";
			string response3 = "need_help";
			
			string_id greeting = new string_id (CONVO,npcGreet);

			string_id response[] = new string_id [3];
			response[0] = new string_id (CONVO, response1);
			response[1] = new string_id (CONVO, response2);
			response[2] = new string_id (CONVO, response3);
			npcStartConversation (speaker, self, "questConvo", greeting, response);
		}
		
		if (zicx == "bugs")
		{
			string npcGreet = "get_the_bile";
			string response1 = "ill_get_bile" ;
			string response2 = "i_quit" ;
			
			string_id greeting = new string_id (CONVO,npcGreet);
			
			string_id response[] = new string_id [2];
			response[0] = new string_id (CONVO, response1);
			response[1] = new string_id (CONVO, response2);
			npcStartConversation (speaker, self, "questConvo", greeting, response);
		}			

		if (zicx == "bile")
		{
			string npcGreet = "get_the_bugs";
			string response1 = "ill_get_bugs" ;
			string response2 = "i_quit" ;
			
			string_id greeting = new string_id (CONVO,npcGreet);
			
			string_id response[] = new string_id [2];
			response[0] = new string_id (CONVO, response1);
			response[1] = new string_id (CONVO, response2);
			npcStartConversation (speaker, self, "questConvo", greeting, response);
		}
			
		if (zicx == "done")
		{
			string npcGreet = "good_work";
			string response1 = "gimme_the_bomb";
						
			string_id greeting = new string_id (CONVO,npcGreet);
			
			string_id response[] = new string_id [1];
			response[0] = new string_id (CONVO, response1);
			npcStartConversation (speaker, self, "questConvo", greeting, response);
		}
		
		if (zicx == "complete")
		{
			string npcGreet = "please_begone";
			string_id greet = new string_id (CONVO, npcGreet);
			chat.chat (self, greet);
			return SCRIPT_CONTINUE;
		}

	}
	return SCRIPT_CONTINUE;
}	

trigger OnNpcConversationResponse (string convo, obj_id player, string_id response)
{

	string response1 = "what_thugs";
	string response2 = "make_me_a_bomb";
	string response3 = "yes_please" ;
	string response4 = "no_thanks" ;
	string response5 = "need_more_time" ;
	string response6 = "i_quit" ;
	string response7 = "ill_get_bile" ;
	string response8 = "ill_get_bugs" ;
	string response9 = "gimme_the_bomb";
	string response10 = "just_passing";
	string response11 = "where_is_jowir"; 
	string response12 = "sarlacc_bile"; 
	string response13 = "on_my_way"; 		
	string response14 = "what_weapon"; 
	string response15 = "still_passing"; 		
	string response16 = "sounds_good"; 		
	string response17 = "need_help"; 		
	
	if ( response.getAsciiId().equals(response1)) //
 	{
 		string npcAnswer = "all_thugs";
 		string_id message = new string_id (CONVO, npcAnswer);//
		npcRemoveConversationResponse (player, new string_id (CONVO,"what_thugs")); 
		npcSpeak(player, message);
		return SCRIPT_CONTINUE;
	}
	
	if ( response.getAsciiId().equals(response2) )
	{
		string npcAnswer = "bombs_are_cool";
		string_id message = new string_id (CONVO, npcAnswer);//
		npcRemoveConversationResponse (player, new string_id (CONVO,"what_thugs")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"make_me_a_bomb")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"just_passing"));
		npcAddConversationResponse (player, new string_id (CONVO,"where_is_jowir")); 
		npcAddConversationResponse (player, new string_id (CONVO,"sarlacc_bile")); 
		npcAddConversationResponse (player, new string_id (CONVO,"on_my_way")); 		
		npcSpeak (player, message);
		obj_id inventory = utils.getInventoryContainer(player);
		createObject ("object/tangible/loot/quest/quest_item_goru_calling_card.iff", inventory, "");
		setObjVar(player, "zicx", "start");
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response3)) //
 	{
 		string npcAnswer = "bombs_are_cool";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
 		obj_id inventory = utils.getInventoryContainer(player);
 		createObject ("object/tangible/loot/quest/quest_item_goru_calling_card.iff", inventory, "");		
 		setObjVar (player, "zicx", "start");
		npcAddConversationResponse (player, new string_id (CONVO,"where_is_jowir")); 
		npcAddConversationResponse (player, new string_id (CONVO,"sarlacc_bile")); 
		npcAddConversationResponse (player, new string_id (CONVO,"on_my_way")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"yes_please")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"no_thanks"));
		return SCRIPT_CONTINUE;
	}
	
	if ( response.getAsciiId().equals(response4) )
	{
		string npcAnswer = "go_away_then";
		string_id message = new string_id (CONVO, npcAnswer);//
		npcSpeak (player, message);
		npcEndConversation(player);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response5)) //
 	{
 		string npcAnswer = "hurry_up";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
	}
	
	if ( response.getAsciiId().equals(response6) )
	{
		string npcAnswer = "fine_quit_then";
		string_id message = new string_id (CONVO, npcAnswer);//
		npcSpeak (player, message);
		setObjVar (player, "zicx", "reset");
		npcEndConversation(player);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response7)) //
 	{
 		string npcAnswer = "bring_me_the_bile";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
	}
	
	if ( response.getAsciiId().equals(response8) )
	{
		string npcAnswer = "bring_me_the_bugs";
		string_id message = new string_id (CONVO, npcAnswer);//
		npcSpeak (player, message);
		npcEndConversation(player);
		return SCRIPT_CONTINUE;
	}
	
	if ( response.getAsciiId().equals(response9)) //
 	{
 		string npcAnswer = "heres_your_bomb";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
 		obj_id inventory = utils.getInventoryContainer(player);
 		createObject ("object/weapon/ranged/grenade/grenade_bug_bomb.iff", inventory, "");
 		setObjVar (player, "zicx", "complete");
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response10)) //
 	{
 		string npcAnswer = "dont_tell_anyone";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcAddConversationResponse (player, new string_id (CONVO,"what_weapon")); 
		npcAddConversationResponse (player, new string_id (CONVO,"still_passing")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"just_passing")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"make_me_a_bomb"));
		npcRemoveConversationResponse (player, new string_id (CONVO,"what_thugs"));
 		npcSpeak(player, message);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response11)) //
 	{
 		string npcAnswer = "in_wayfar";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcRemoveConversationResponse (player, new string_id (CONVO,"where_is_jowir")); 
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response12)) //
 	{
 		string npcAnswer = "no_idea";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcRemoveConversationResponse (player, new string_id (CONVO,"sarlacc_bile")); 
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response13)) //
 	{
 		string npcAnswer = "good_luck";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response14)) //
 	{
 		string npcAnswer = "zicx_bomb";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
 		npcRemoveConversationResponse (player, new string_id (CONVO,"what_weapon")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"still_passing")); 
		npcAddConversationResponse (player, new string_id (CONVO, "sounds_good"));
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response15)) //
 	{
 		string npcAnswer = "dont_say_nothing";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		npcSpeak(player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response16)) //
 	{
 		string npcAnswer = "see_jowir";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		setObjVar (player, "zicx", "start");
 		npcSpeak(player, message);
 		npcRemoveConversationResponse (player, new string_id (CONVO,"sounds_good")); 

		npcAddConversationResponse (player, new string_id (CONVO,"where_is_jowir")); 
		npcAddConversationResponse (player, new string_id (CONVO,"on_my_way")); 
 		obj_id inventory = utils.getInventoryContainer(player);
 		createObject ("object/tangible/loot/quest/quest_item_goru_calling_card.iff", inventory, "");		
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals(response17)) //
 	{
 		string npcAnswer = "more_info";
 		string_id message = new string_id (CONVO, npcAnswer);//
 		
 		npcSpeak(player, message);
 		npcRemoveConversationResponse (player, new string_id (CONVO,"need_more_time")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"i_quit")); 
		npcRemoveConversationResponse (player, new string_id (CONVO,"need_help")); 
		
		npcAddConversationResponse (player, new string_id (CONVO,"where_is_jowir")); 
		npcAddConversationResponse (player, new string_id (CONVO,"sarlacc_bile")); 
		npcAddConversationResponse (player, new string_id (CONVO,"on_my_way")); 		
		return SCRIPT_CONTINUE;
	}

	
	return SCRIPT_CONTINUE;
}	

trigger OnGiveItem(obj_id item, obj_id player)
{
	if (!hasObjVar (player, "zicx"))
	{
		debugSpeakMsg (self, "I don't know you.");
		return SCRIPT_OVERRIDE;
	}
	
	string name = getTemplateName (item);
	string zicx = getStringObjVar (player, "zicx");
	
	if (name == "object/tangible/loot/quest/quest_item_zicx_bug_jar.iff")
	{
		if (zicx == "bile")
		{
			string_id finishMessage = new string_id (CONVO, "give_a_minute");
			chat.chat (self, finishMessage);
			destroyObject (item);
			setObjVar (player, "zicx", "done");
		}
		else
		{
			string_id finishMessage = new string_id (CONVO, "bring_me_the_bile");
			chat.chat (self, finishMessage);
			destroyObject (item);
			setObjVar (player, "zicx", "bugs");
		}			
	}
	else if (name == "object/tangible/loot/quest/quest_item_sarlacc_bile_jar.iff")
	{
		if (zicx == "bugs")
		{
			string_id finishMessage = new string_id (CONVO, "give_a_minute");
			chat.chat (self, finishMessage);
			destroyObject (item);
			setObjVar (player, "zicx", "done");
		}
		else
		{
			string_id finishMessage = new string_id (CONVO, "bring_me_the_bugs");
			chat.chat (self, finishMessage);
			destroyObject (item);
			setObjVar (player, "zicx", "bile");
		}			
	}
	else
	{
		string_id npcwhat = new string_id (CONVO, "what_is_this");
		chat.chat (self, npcwhat);
	}		
	return SCRIPT_CONTINUE;
}