include library.space_transition;

trigger OnAttach()
{
	sendSystemMessageTestingOnly( self, "Greeting, Human!  To begin applying the smackdown, say PVP ON");
	sendSystemMessageTestingOnly( self, "To discontinue the laying down of the smack, say PVP OFF");
	return SCRIPT_CONTINUE;
}

trigger OnSpeaking( string text)
{
	if ( text.equalsIgnoreCase( "pvp on" ) )
	{
		if (isSpaceScene())
		{
			space_transition.setPlayerOvert( self, ##"imperial" );
			sendSystemMessageTestingOnly( self, "Just start killing Bothans. I'll tell you when to stop.");
		}
		else
			sendSystemMessageTestingOnly( self, "With what? Your HANDS?! You have to be in space, yo.");
	}
	else if ( text.equalsIgnoreCase( "pvp off" ) )
	{
		if (isSpaceScene())
		{
			obj_id ship = space_transition.getContainingShip(self);
			space_transition.clearOvertStatus( ship );
			sendSystemMessageTestingOnly( self, "Ah! Safe, but never innocent. No wonder she still weeps for you.");
		}
		else
			sendSystemMessageTestingOnly( self, "It is very dark. You are likely to be eaten by a Grue.");

	}
	return SCRIPT_CONTINUE;
}

