
include library.sui;
include library.utils;
include library.minigame;

trigger OnDetach()
{
	minigame.cleanupFishing(self);
	return SCRIPT_CONTINUE;
}

trigger OnEnteredCombat()
{
	minigame.stopFishing(self);
	return SCRIPT_CONTINUE;
}

/*messageHandler handleFishingSui()
{
	return SCRIPT_CONTINUE;
}*/

messageHandler handleFishingTick()
{
	return SCRIPT_CONTINUE;
}

messageHandler handlePlayCastSplash()
{
	minigame.playCastSplash(self, params);
	messageTo(self, minigame.HANDLER_FISHING_TICK, null, minigame.FISHING_TICK, false);
	return SCRIPT_CONTINUE;
}