//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SwgSpaceQuestEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_DIRECTORY            101
#define IDD_FORM_PROPERTYVIEW           102
#define IDD_FORM_SLOTVIEW               103
#define IDD_FORM_ATTRIBUTEVIEW          104
#define IDD_FORM_EMPTYVIEW              105
#define IDD_DIALOG_CONSOLE              106
#define IDR_MAINFRAME                   128
#define IDR_SWGDRATYPE                  129
#define IDB_BITMAP_DIRECTORY            132
#define IDB_BITMAP_SPACEQUEST           133
#define IDR_MENU_CONTEXT                136
#define IDD_DIALOG_RESOURCE             137
#define IDD_DIALOG_MISSIONTEMPLATE      140
#define IDD_DIALOG_SPACEMOBILELIST      141
#define IDD_DIALOG_SPACEMOBILE          142
#define IDD_DIALOG_NAVPOINT             143
#define IDD_DIALOG_NAVPOINTLIST         144
#define IDD_DIALOG_STRINGEDIT           145
#define IDD_DIALOG_STRINGIDLIST         147
#define IDD_DIALOG_CARGO                148
#define IDC_TREEVIEW                    1000
#define IDC_EDIT_INGREDIENTCOUNT        1001
#define IDC_EDIT_INGREDIENTNAME         1002
#define IDC_EDIT_EXPERIMENTSTRINGTABLE  1005
#define IDC_BUTTON_BROWSESERVERCRAFTEDOBJECTTEMPLATE 1005
#define IDC_EDIT_EXPERIMENTSTRINGID     1006
#define IDC_BUTTON_BROWSEINGREDIENTNAME 1006
#define IDC_BUTTON_BROWSESHAREDCRAFTEDOBJECTTEMPLATE 1007
#define IDC_CHECK_OPTIONAL              1008
#define IDC_COMBO_INGREDIENTTYPE        1009
#define IDC_EDIT_NAMESTRINGTABLE        1010
#define IDC_EDIT_NAMESTRINGID           1011
#define IDC_COMBO_SERVERBASESPACEQUEST  1013
#define IDC_EDIT_ITEMSPERCONTAINER      1014
#define IDC_EDIT_COMPLEXITY             1015
#define IDC_EDIT_SERVERCRAFTEDOBJECTTEMPLATE 1016
#define IDC_EDIT_MANUFACTURESCRIPT      1017
#define IDC_EDIT_SHAREDCRAFTEDOBJECTTEMPLATE 1018
#define IDC_BUTTON_BROWSEMANUFACTURESCRIPT 1019
#define IDC_EDIT_OUTPUT                 1020
#define IDC_COMBO_OVERRIDEXPTYPEVALUE   1021
#define IDC_EDIT_SHELL                  1021
#define IDC_RADIO_VALUETYPE             1022
#define IDC_EDIT_SERVEROLD              1022
#define IDC_EDIT_WARNING                1022
#define IDC_COMBO_MINIMUM               1023
#define IDC_EDIT_SERVERNEW              1023
#define IDC_EDIT_CONFIGURATION          1023
#define IDC_COMBO_MAXIMUM               1024
#define IDC_EDIT_SHAREDOLD              1024
#define IDC_RADIO_VALUETYPEARMORRATING  1025
#define IDC_EDIT_SHAREDNEW              1025
#define IDC_RADIO_VALUETYPEDAMAGETYPE   1026
#define IDC_EDIT_MAXIMUM                1027
#define IDC_EDIT_MINIMUM                1028
#define IDC_CHECK_OVERRIDEDESTROYINGREDIENTVALUE 1028
#define IDC_CHECK_OVERRIDEDESTROYINGREDIENT 1029
#define IDC_COMBO_OVERRIDECRAFTINGTYPEVALUE 1030
#define IDC_CHECK_OVERRIDEXPTYPE        1031
#define IDC_CHECK_OVERRIDECRAFTINGTYPE  1032
#define IDC_BUTTON_GENERATESHAREDCRAFTEDOBJECTTEMPLATENAME 1033
#define IDC_TREE_RESOURCE               1034
#define IDC_TAB_SELECTOR                1036
#define IDC_COMBO_NAMESTRINGTABLE       1037
#define IDC_LIST_MISSIONTEMPLATE        1038
#define IDC_LIST_SPACEMOBILE            1039
#define IDC_BUTTON_ADD                  1040
#define IDC_BUTTON_REMOVE               1041
#define IDC_BUTTON_UP                   1042
#define IDC_BUTTON_DOWN                 1043
#define IDC_BUTTON_REMOVEALL            1044
#define IDC_TREE_NAVPOINT               1046
#define IDC_BUTTON_EDIT                 1048
#define IDC_EDIT_CUSTOM                 1049
#define IDC_EDIT1                       1050
#define IDC_BUTTON1                     1051
#define IDC_BUTTON2                     1052
#define IDC_BUTTON3                     1053
#define IDC_BUTTON0                     1054
#define IDC_EDIT_STRINGID               1056
#define IDC_LIST_STRINGID               1057
#define IDC_BUTTON_CHANGE               1058
#define IDC_LIST_CARGO                  1059
#define ID_PROPERTYLIST                 10000
#define ID_STRINGLIST                   10001
#define ID_QUESTSTRINGLIST              10002
#define ID_FILE_CLOSEALL                32771
#define ID_TOOLS_OPENALL                32772
#define ID_TREE_ADDSLOT                 32774
#define ID_TREE_ADDATTRIBUTE            32775
#define ID_TREE_DELETE                  32776
#define ID_BUTTON_COMPILE               32780
#define ID_BUTTON_SAVETEST              32784
#define ID_VIEW_CONSOLE                 32786
#define ID_VIEW_DIRECTORY               32787
#define ID_EDIT_STRINGIDLIST            32790
#define ID_TOOLS_SCANALL                32792
#define ID_BUTTON_INFORMATION           32793
#define ID_TOOLS_OPENSAVEALL            32794
#define ID_TOOLS_OPENEDITALL            32795
#define ID_APP_HELP                     32809
#define ID_BUTTON_COMPILEDEBUG          32810
#define ID_BUTTON_P4EDIT                32812
#define ID_BUTTON_SCAN                  32815
#define ID_INDICATOR_TOOLTIP            59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
