include library.hue;
include library.utils;
include library.ai_lib;
include library.factions;
include library.space_flags;

inherits theme_park.recruitment.base.base_recruiter;

const string CONVO						= "recruiting/imperial_recruit";

trigger OnInitialize()
{
	if (!hasObjVar (self, "dressed"));
	{
		obj_id suit = createObject ("object/tangible/wearables/bodysuit/bodysuit_tie_fighter.iff", self, "");
		obj_id boots = createObject ("object/tangible/wearables/boots/boots_s03.iff", self, "");
		hue.hueObject (self);
		pvpSetAlignedFaction (self, ##"imperial");
		pvpMakeDeclared(self);
		string hair_table = "datatables/npc_customization/human_male_hair.iff";
		int numHair = dataTableGetNumRows (hair_table);
		int hairCol = dataTableGetNumColumns (hair_table);
		hairCol = hairCol - 1;
		numHair = numHair - 1;
		hairCol = rand (1, hairCol);
		numHair = rand (1, numHair);
		string hair = dataTableGetString ( hair_table, numHair, hairCol );
		obj_id hairStyle = createObject (hair, self, "");
		hue.hueObject (hairStyle);
		setObjVar (self, "dressed", 1);
	}

	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );

	return SCRIPT_CONTINUE;
}

trigger OnStartNpcConversation (obj_id speaker)
{
	if (ai_lib.isInCombat(self) || ai_lib.isInCombat(speaker))
		return SCRIPT_OVERRIDE;

	string_id greeting = new string_id (CONVO, "ir1"); // The wind whistles...
	resizeable string_id[] response = new string_id[0];

	boolean addRedeemOption = false;

	//do factional data item stuff here

	string faction = factions.getFaction (speaker);

	if (faction != null)
	{
		if (faction == factions.FACTION_REBEL)
		{
			greeting = new string_id (CONVO, "ir16"); // I don't think either...
			response = utils.addElement(response, new string_id (CONVO, "ir17")); // Sorry.
		}
		else if (faction == factions.FACTION_IMPERIAL)
		{
			greeting = new string_id (CONVO, "ir13"); // Good day, sir...
			response = utils.addElement(response, new string_id (CONVO, "ir14")); // I'm tired of being an imperial...
		}
	}
	else
	{
		greeting = new string_id (CONVO, "ir1"); // Good afternoon...
		response = utils.addElement(response, new string_id (CONVO, "ir2")); // Yes, I'm interested in joining...
		response = utils.addElement(response, new string_id (CONVO, "ir3")); // No thank you.
	}

	if ( addRedeemOption )
	{
		response = utils.addElement(response, new string_id(DATA_ITEM_CONVO, "redeem"));
	}

	if ( (response == null) || (response.length == 0) )
	{
		return SCRIPT_OVERRIDE;
	}
	else
	{
		npcStartConversation (speaker, self, CONVO, greeting, response);
	}

	return SCRIPT_CONTINUE;
}


trigger OnNpcConversationResponse (string convo, obj_id player, string_id response)
{
	if ( response.getTable().equals(DATA_ITEM_CONVO) )
	{
		//do factional data item stuff here
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals("ir2")) // Yes, I'm interested in joining...
 	{
		string_id message = new string_id (CONVO, "ir4"); //
		npcSpeak(player, message);
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir2")); //
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir3")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir5")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir6")); //
		return SCRIPT_CONTINUE;
 	}

	if ( response.getAsciiId().equals("ir3")) //
 	{
		string_id message = new string_id (CONVO, "ir11"); //
		npcSpeak (player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
 	}

	if ( response.getAsciiId().equals("ir5") ) //
	{
		string_id message = new string_id (CONVO, "ir7"); //
		npcSpeak(player, message);
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir5")); //
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir6")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir8")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir9")); //
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals("ir6") ) //
	{
		string_id message = new string_id (CONVO, "ir7"); //
		npcSpeak(player, message);
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir5")); //
		npcRemoveConversationResponse(player, new string_id (CONVO,"ir6")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir8")); //
		npcAddConversationResponse( player, new string_id (CONVO,"ir9")); //
		return SCRIPT_CONTINUE;
	}

	if ( response.getAsciiId().equals("ir8")) //
 	{
		string_id message = new string_id (CONVO, "ir12"); //
		pvpSetAlignedFaction ( player, ##"imperial");
		pvpMakeDeclared (player);
		setObjVar (player, "imperial", 1);
		npcSpeak (player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
 	}

	if ( response.getAsciiId().equals("ir9")) //
 	{
		string_id message = new string_id (CONVO, "ir10"); //
		npcSpeak (player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
 	}
 	if (response.getAsciiId().equals("ir14")) //I dont think...
	{
		string_id message = new string_id (CONVO, "ir15"); //Ok, you're out
		npcSpeak (player, message);
		npcEndConversation (player);

		//this automatically clears their aligned faction and
		// sets their pvpType to NEUTRAL:
		pvpSetAlignedFaction(self,0);
		pvpMakeNeutral(self);

		//if they are pilots, set their alignedFaction (they'll still be pvp Type neutral)
		if ( space_flags.isImperialPilot(self) )
			pvpSetAlignedFaction( self, ##"imperial" );
		else if ( space_flags.isRebelPilot(self) )
			pvpSetAlignedFaction( self, ##"rebel" );

		removeObjVar (player, "rebel");
		return SCRIPT_CONTINUE;
	}
	if ( response.getAsciiId().equals("ir17")) // Sorry
 	{
		string_id message = new string_id (CONVO, "ir18"); // Just go on about your business.
		npcSpeak (player, message);
		npcEndConversation (player);
		return SCRIPT_CONTINUE;
 	}

	return SCRIPT_CONTINUE;
 }
