//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TerrainEditor.rc
//
#define CG_IDC_PROGDLG_PERCENT          1000
#define CG_IDC_PROGDLG_PROGRESS         1001
#define CG_IDD_PROGRESS                 1002
#define CG_IDP_FILE_CORRUPT             1003
#define CG_IDS_DIDYOUKNOW               1004
#define CG_IDS_FILE_ABSENT              1005
#define CG_IDS_PROGRESS_CAPTION         1006
#define CG_IDS_PROGRESS_CAPTION2        1007
#define CG_IDS_TIPOFTHEDAY              1008
#define CG_IDS_TIPOFTHEDAYHELP          1009
#define CG_IDS_TIPOFTHEDAYMENU          1010
#define IDB_BITMAP_CATALOG              1011
#define IDB_BITMAP_FAMILY               1012
#define IDB_BITMAP_LAYER                1013
#define IDB_BITMAP_LISTVIEW_HEADER      1014
#define IDB_BITMAP_WARNING              1015
#define IDB_LIGHTBULB                   1016
#define IDB_NEWNAME                     1017
#define IDB_SPLASH                      1018
#define IDC_ADD                         1019
#define IDC_ALIGN_TO_TERRAIN            1020
#define IDC_AMPLITUDE                   1021
#define IDC_BIAS                        1022
#define IDC_BROWSE                      1023
#define IDC_BULB                        1024
#define IDC_BUTTON_BROWSE               1025
#define IDC_BUTTON_GLOBALWATERSHADERBROWSE 1026
#define IDC_BUTTON_REFRESH              1027
#define IDC_BUTTON_SHADER_BROWSE        1028
#define IDC_CATALOG_TREE                1029
#define IDC_CHECK_ALIGNTOTERRAIN        1030
#define IDC_BUTTON_CLOUD_SHADER_BROWSE  1030
#define IDC_CHECK_BIAS                  1031
#define IDC_BUTTON_AMBIENTSOUNDBROWSE   1031
#define IDC_CHECK_CHANGE_DISPLACEMENT   1032
#define IDC_CHECK_CHANGE_PERIOD         1033
#define IDC_MUSIC_FIRST_BROWSE          1033
#define IDC_CHECK_CHANGE_SWAY           1034
#define IDC_CHECK_CLEAR                 1035
#define IDC_CHECK_DENSITYOVERRIDE       1036
#define IDC_CHECK_FLOATS                1037
#define IDC_CHECK_GAIN                  1038
#define IDC_CHECK_GRID_ENABLED          1039
#define IDC_CHECK_HASWATER              1040
#define IDC_CHECK_INVERT_BOUNDARIES     1041
#define IDC_CHECK_INVERT_FILTERS        1042
#define IDC_CHECK_ISWATERTABLE          1043
#define IDC_CHECK_REMOVE_ALL_FLORA      1044
#define IDC_CHECK_REMOVE_ALL_RADIAL     1045
#define IDC_CHECK_SCALE                 1046
#define IDC_CHECK_SWAY                  1047
#define IDC_CHECK_USEGLOBALWATER        1048
#define IDC_CHILDRENLIST                1049
#define IDC_CHECK_USEGLOBALMUSIC        1049
#define IDC_CHOOSECOLOR                 1050
#define IDC_COMBINATIONRULE             1051
#define IDC_COMBO_CHUNK_WIDTH           1052
#define IDC_COMBO_FILTEROPERATION       1053
#define IDC_COMBO_MAPWIDTH              1054
#define IDC_COMBO_SHADER_SIZE           1055
#define IDC_COMBO_TILES_PER_CHUNK       1056
#define IDC_CREATE_PLUS                 1057
#define IDC_CURSOR_CIRCLE               1058
#define IDC_MAINTAIN_ASPECT_RATIO       1058
#define IDC_CURSOR_COPY                 1059
#define IDC_CURSOR_MOVE                 1060
#define IDC_CURSOR_POLYGON              1061
#define IDC_CURSOR_POLYLINE             1062
#define IDC_CURSOR_RECTANGLE            1063
#define IDC_CURSOR_ZOOM_IN              1064
#define IDC_CURSOR_ZOOM_OUT             1065
#define IDC_CX                          1066
#define IDC_CZ                          1067
#define IDC_EDIT1                       1068
#define IDC_EDIT_C_MAXDISTANCE          1069
#define IDC_EDIT_MINUTES                1069
#define IDC_EDIT_C_MINDISTANCE          1070
#define IDC_CLOUD_SHADER                1070
#define IDC_EDIT_C_SEED                 1071
#define IDC_AMBIENTSOUNDFILENAME        1071
#define IDC_EDIT_C_TILEBORDER           1072
#define IDC_EDIT_C_TILESIZE             1073
#define IDC_MUSIC_FIRST                 1073
#define IDC_EDIT_C_TOTALFLORA           1074
#define IDC_EDIT_DENSITY                1075
#define IDC_EDIT_DISPLACEMENT           1076
#define IDC_EDIT_DISTANCE               1077
#define IDC_EDIT_ENDX                   1078
#define IDC_EDIT_ENDZ                   1079
#define IDC_EDIT_FAMILY_NAME            1080
#define IDC_EDIT_FREQUENCY              1081
#define IDC_EDIT_F_MAXDISTANCE          1082
#define IDC_EDIT_F_MINDISTANCE          1083
#define IDC_EDIT_F_SEED                 1084
#define IDC_EDIT_F_TILEBORDER           1085
#define IDC_EDIT_F_TILESIZE             1086
#define IDC_EDIT_F_TOTALFLORA           1087
#define IDC_EDIT_GLOBALWATERHEIGHT      1088
#define IDC_EDIT_GLOBALWATERSHADER      1089
#define IDC_EDIT_GLOBALWATERSHADERSIZE  1090
#define IDC_EDIT_HEIGHT                 1091
#define IDC_EDIT_HEIGHTPOLEDISTANCE     1092
#define IDC_EDIT_IMAGENAME              1093
#define IDC_EDIT_MAXHEIGHT              1094
#define IDC_EDIT_GLOBALMUSIC            1094
#define IDC_EDIT_MAXIMUM_SCALE          1095
#define IDC_EDIT_MINHEIGHT              1096
#define IDC_EDIT_MINIMUM_SCALE          1097
#define IDC_EDIT_NOTES                  1098
#define IDC_EDIT_N_MAXDISTANCE          1099
#define IDC_EDIT_N_MINDISTANCE          1100
#define IDC_EDIT_N_SEED                 1101
#define IDC_EDIT_N_TILEBORDER           1102
#define IDC_EDIT_N_TILESIZE             1103
#define IDC_EDIT_N_TOTALFLORA           1104
#define IDC_EDIT_R_MAXDISTANCE          1105
#define IDC_EDIT_R_MINDISTANCE          1106
#define IDC_EDIT_R_SEED                 1107
#define IDC_EDIT_R_TILEBORDER           1108
#define IDC_EDIT_R_TILESIZE             1109
#define IDC_EDIT_R_TOTALFLORA           1110
#define IDC_EDIT_SHADER                 1111
#define IDC_EDIT_SHADERSIZE             1112
#define IDC_EDIT_STARTX                 1113
#define IDC_EDIT_STARTZ                 1114
#define IDC_EDIT_TILESIZE               1115
#define IDC_EDIT_TRENCHDEPTH            1116
#define IDC_EDIT_VELOCITY               1117
#define IDC_EDIT_WATERDEPTH             1118
#define IDC_EDIT_WATERWIDTH             1119
#define IDC_EDIT_WIDTH                  1120
#define IDC_EDIT_MINWIDTH               1120
#define IDC_EDIT_WIDTH2                 1121
#define IDC_EDIT_MAXWIDTH               1121
#define IDC_FAMILY                      1122
#define IDC_EDIT_CAP_WIDTH              1122
#define IDC_FAMILY_BANK                 1123
#define IDC_EDIT_DEPTH                  1123
#define IDC_FAMILY_BOTTOM               1124
#define IDC_EDIT_SHADER_SIZE            1124
#define IDC_EDIT_WATER_SHADER_SIZE      1124
#define IDC_FEATHER_DISTANCE            1125
#define IDC_WATER_TYPE                  1125
#define IDC_FEATHER_FUNCTION            1126
#define IDC_TERRAIN_SHADER_FAMILY       1126
#define IDC_FILENAME                    1127
#define IDC_FEATHER_DISTANCESHADER      1127
#define IDC_WATER_TYPE2                 1127
#define IDC_FLATRATIO                   1128
#define IDC_FEATHER_FUNCTIONSHADER      1128
#define IDC_FREQUENCY                   1129
#define IDC_GAIN                        1130
#define IDC_HEIGHT                      1131
#define IDC_HIGH                        1132
#define IDC_HIGHHEIGHT                  1133
#define IDC_BITMAP_GAIN                 1133
#define IDC_HIGHHT                      1134
#define IDC_INFO                        1135
#define IDC_LIST_DESTINATION            1136
#define IDC_LIST_SOURCE                 1137
#define IDC_LOW                         1138
#define IDC_LOWHEIGHT                   1139
#define IDC_LOWHT                       1140
#define IDC_MAXANGLEDEG                 1141
#define IDC_MINANGDEG                   1142
#define IDC_NAME                        1143
#define IDC_NEXTTIP                     1144
#define IDC_OCTAVES                     1145
#define IDC_OFFSETX                     1146
#define IDC_OFFSETZ                     1147
#define IDC_OPERATION                   1148
#define IDC_RADIO1                      1149
#define IDC_REPLACE                     1150
#define IDC_RX                          1151
#define IDC_SCALE                       1152
#define IDC_SCALEX                      1153
#define IDC_SCALEY                      1154
#define IDC_SCALEZ                      1155
#define IDC_SEED                        1156
#define IDC_SLIDER_AMPLITUDE            1157
#define IDC_SLIDER_BIAS                 1158
#define IDC_SLIDER_DENSITY              1159
#define IDC_SLIDER_FEATHERDISTANCE      1160
#define IDC_SLIDER_FLATRATIO            1161
#define IDC_SLIDER_FEATHERDISTANCESHADER 1161
#define IDC_SLIDER_FREQUENCY            1162
#define IDC_SLIDER_GAIN                 1163
#define IDC_SLIDER_HIGH                 1164
#define IDC_SLIDER_LOW                  1165
#define IDC_SLIDER_OCTAVES              1166
#define IDC_SLIDER_BITMAP_GAIN          1166
#define IDC_SLIDER_SCALEX               1167
#define IDC_SLIDER_SCALEZ               1168
#define IDC_STARTUP                     1169
#define IDC_STATIC_FAMILY_COLOR         1170
#define IDC_STATIC_WINDOW_COLOR         1171
#define IDC_SUBTRACT                    1172
#define IDC_TIPSTRING                   1173
#define IDC_TODESTINATION               1174
#define IDC_TOSOURCE                    1175
#define IDC_TREELIST_VIEW               1176
#define IDC_VALUE                       1177
#define IDC_WEIGHT                      1178
#define IDC_WIDTH                       1179
#define IDC_X0                          1180
#define IDC_X1                          1181
#define IDC_Z0                          1182
#define IDC_Z1                          1183
#define IDD_ABOUTBOX                    1184
#define IDD_DEFAULT_PROPVIEW            1185
#define IDD_DIALOG_CATALOG              1186
#define IDD_DIALOG_FIND                 1187
#define IDD_DIALOG_FLORAGLOBALSWAY      1188
#define IDD_DIALOG_FLORAPARAMETERS      1189
#define IDD_DIALOG_MAPPARAMETERS        1190
#define IDD_DIALOG_PREFERENCES          1191
#define IDD_FORM_AFFECTORCOLORBITMAP    1192
#define IDD_FORM_AFFECTORCOLORCONSTANT  1193
#define IDD_FORM_AFFECTORCOLORRAMPFRACTAL 1194
#define IDD_FORM_AFFECTORCOLORRAMPHEIGHT 1195
#define IDD_FORM_AFFECTORFLORACONSTANT  1196
#define IDD_FORM_AFFECTORHEIGHTBITMAP   1197
#define IDD_FORM_AFFECTORHEIGHTCONSTANT 1198
#define IDD_FORM_AFFECTORHEIGHTFRACTAL  1199
#define IDD_FORM_AFFECTORHEIGHTTERRACE  1200
#define IDD_FORM_AFFECTORRADIALCONSTANT 1201
#define IDD_FORM_AFFECTORRADIALFAMILY   1202
#define IDD_FORM_AFFECTORRIVER          1203
#define IDD_FORM_AFFECTORROAD           1204
#define IDD_FORM_AFFECTORSHADERBITMAP   1205
#define IDD_FORM_AFFECTORSHADERCONSTANT 1206
#define IDD_FORM_BOUNDARYCIRCLE         1207
#define IDD_FORM_BOUNDARYPOLYGON        1208
#define IDD_FORM_BOUNDARYPOLYLINE       1209
#define IDD_FORM_BOUNDARYRECT           1210
#define IDD_FORM_FILTERDIRECTION        1211
#define IDD_FORM_FILTERFRACTAL          1212
#define IDD_FORM_FILTERHEIGHT           1213
#define IDD_FORM_FILTERSHADER           1214
#define IDD_FORM_FILTERSLOPE            1215
#define IDD_FORM_FLORACHILD             1216
#define IDD_FORM_FLORAFAMILY            1217
#define IDD_FORM_LAYER                  1218
#define IDD_FORM_RADIALCHILD            1219
#define IDD_FORM_RADIALFAMILY           1220
#define IDD_FORM_SHADERCHILD            1221
#define IDD_FORM_SHADERFAMILY           1222
#define IDD_FORM_TEMPLATE               1223
#define IDD_TIP                         1224
#define IDD_TREELIST_VIEW               1225
#define IDR_BLENDGROUPFRAME             1226
#define IDR_BOOKMARKFRAME               1227
#define IDR_FINDVIEW_MENU               1228
#define IDR_FLORAGROUPFRAME             1229
#define IDR_GROUP_MENU                  1230
#define IDR_HELPVIEW                    1231
#define IDR_LAYERVIEW                   1232
#define IDR_LAYERVIEW_MENU              1233
#define IDR_MAINFRAME                   1234
#define IDR_MAPVIEW                     1235
#define CG_IDS_PROGRESS_CAPTION_FLORABAKE 1235
#define IDR_MAPVIEW2                    1236
#define IDR_MENU_CATALOG                1237
#define IDR_PROPERTYVIEW                1238
#define IDR_RADIALGROUPFRAME            1239
#define IDR_SHADERGROUPFRAME            1240
#define IDR_TERRAITYPE                  1241
#define IDR_VIEW3D                      1242
#define IDR_WATERFRAME                  1243
#define IDS_AMPLITUDE                   1244
#define IDR_ENVIRONMENTFRAME            1244
#define IDR_ENVIRONMENTGROUPFRAME       1244
#define IDS_BIAS                        1245
#define IDR_FRACTALGROUPFRAME           1245
#define IDS_COMBINATIONRULE             1246
#define IDR_BITMAPGROUPFRAME            1246
#define IDS_FEATHERDISTANCEFLOAT        1247
#define IDS_FEATHERDISTANCEMETERS       1248
#define IDS_FEATHERFUNCTION             1249
#define IDS_FREQUENCY                   1250
#define IDS_GAIN                        1251
#define IDS_HIGH                        1252
#define IDS_LOW                         1253
#define IDS_NUMBEROFOCTAVES             1254
#define IDS_SCALEX                      1255
#define IDS_SCALEZ                      1256
#define IDS_SEED                        1257
#define ID_3D_VIEW                      1258
#define ID_APPLY                        1259
#define ID_BCIRCLEMODE                  1260
#define ID_BPOLYMODE                    1261
#define ID_BRECTMODE                    1262
#define ID_BUTTON32790                  1263
#define ID_BUTTON32815                  1264
#define ID_BUTTON32816                  1265
#define ID_BUTTON32817                  1266
#define ID_BUTTON_APPLY                 1267
#define ID_BUTTON_BACK                  1268
#define ID_BUTTON_CALCULATECOLOR        1269
#define ID_BUTTON_DELETEUNUSED          1270
#define ID_BUTTON_DELETE_LAYER          1271
#define ID_BUTTON_DEMOTE_LAYER          1272
#define ID_BUTTON_FLORAGROUP_DELETEFAMILY 1273
#define ID_BUTTON_FLORAGROUP_FINDTARGET 1274
#define ID_BUTTON_FLORAGROUP_NEWCHILD   1275
#define ID_BUTTON_FLORAGROUP_NEWFAMILY  1276
#define ID_BUTTON_FORWARD               1277
#define ID_BUTTON_HOME                  1278
#define ID_BUTTON_LAYERVIEW             1279
#define ID_BUTTON_NEWACTION             1280
#define ID_BUTTON_NEWLAYER              1281
#define ID_BUTTON_NEWROOTLAYER          1282
#define ID_BUTTON_NEWSUBLAYER           1283
#define ID_BUTTON_PROMOTE_LAYER         1284
#define ID_BUTTON_PUSHROOT              1285
#define ID_BUTTON_PUSHUP                1286
#define ID_BUTTON_RADIALGROUP_DELETEFAMILY 1287
#define ID_BUTTON_RADIALGROUP_FINDTARGET 1288
#define ID_BUTTON_RADIALGROUP_NEWCHILD  1289
#define ID_BUTTON_RADIALGROUP_NEWFAMILY 1290
#define ID_BUTTON_REFRESH               1291
#define ID_BUTTON_SHOW_BOUNDARIES       1292
#define ID_BUTTON_SHOW_PROFILE          1293
#define ID_BUTTON_SHOW_RIVERS           1294
#define ID_BUTTON_SHOW_ROADS            1295
#define ID_BUTTON_STOP                  1296
#define ID_BUTTON_SWAYALL               1297
#define ID_BUTTON_SWAYFAMILY            1298
#define ID_CREATECIRCLE                 1299
#define ID_CREATEPOLYGON                1300
#define ID_CREATEPOLYLINE               1301
#define ID_CREATERECTANGLE              1302
#define ID_CREATERIVER                  1303
#define ID_CREATEROAD                   1304
#define ID_DELETEBOOKMARK               1305
#define ID_DELETESHADER                 1306
#define ID_DELETEWATER                  1307
#define ID_DEMOTESHADER                 1308
#define ID_EDITBOOKMARK                 1309
#define ID_EDIT_BLENDS                  1310
#define ID_EDIT_FLORA                   1311
#define ID_EDIT_FRACTAL                 1312
#define ID_EDIT_RADIAL                  1313
#define ID_EDIT_SHADERS                 1314
#define ID_EDIT_SHADER_SIZE             1315
#define ID_EXPORT_LAYERITEM             1316
#define ID_FINDSHADER                   1317
#define ID_FINDVIEW_CLEAR               1318
#define ID_FINDVIEW_FINDBYNAME          1319
#define ID_FINDVIEW_FINDBYTYPE          1320
#define ID_FRACTAL_PREVIEW              1321
#define ID_FREEZEMAP                    1322
#define ID_GRID                         1323
#define ID_GROUP_DELETE                 1324
#define ID_GROUP_RENAME                 1325
#define ID_INDICATOR_2D_MAP_POSITION    1326
#define ID_INDICATOR_FLORADYNAMICFAR    1327
#define ID_INDICATOR_FLORADYNAMICNEAR   1328
#define ID_INDICATOR_FLORASTATICCOLLIDABLE 1329
#define ID_INDICATOR_FLORASTATICNONCOLLIDABLE 1330
#define ID_INDICATOR_SHADER             1331
#define ID_INDICATOR_ZOOM_LEVEL         1332
#define ID_INSERT_COLLAPSEALL           1333
#define ID_INSERT_COLLAPSEBRANCH        1334
#define ID_INSERT_DELETE                1335
#define ID_INSERT_EXPANDALL             1336
#define ID_INSERT_EXPANDBRANCH          1337
#define ID_INSERT_IMPORT_AFFECTOR       1338
#define ID_INSERT_IMPORT_BOUNDARY       1339
#define ID_INSERT_IMPORT_FILTER         1340
#define ID_INSERT_IMPORT_LAYER          1341
#define ID_INSERT_RENAME                1342
#define ID_INSERT_SCAN_ALL              1343
#define ID_INSERT_SCAN_DUMP             1344
#define ID_INSERT_SCAN_LAYER            1345
#define ID_LIGHTING                     1346
#define ID_MODIFYPOLYGON                1347
#define ID_MODIFYPOLYLINE               1348
#define ID_MODIFYRIVER                  1349
#define ID_MODIFYROAD                   1350
#define ID_NEWBOOKMARK                  1351
#define ID_NEWLAYER                     1352
#define ID_NEWSHADERCHILD               1353
#define ID_NEWSHADERFAMILY              1354
#define ID_NEW_AFFECTOR_COLOR_BITMAP    1355
#define ID_NEW_AFFECTOR_COLOR_CONSTANT  1356
#define ID_NEW_AFFECTOR_COLOR_RAMPFRACTAL 1357
#define ID_NEW_AFFECTOR_COLOR_RAMPHEIGHT 1358
#define ID_NEW_AFFECTOR_EXCLUDE         1359
#define ID_NEW_AFFECTOR_FLORA_COLLIDABLE_CONSTANT 1360
#define ID_NEW_AFFECTOR_FLORA_DYNAMICFAR_CONSTANT 1361
#define ID_NEW_AFFECTOR_FLORA_DYNAMICNEAR_CONSTANT 1362
#define ID_NEW_AFFECTOR_FLORA_NONCOLLIDABLE_CONSTANT 1363
#define ID_NEW_AFFECTOR_HEIGHT_BITMAP   1364
#define ID_NEW_AFFECTOR_HEIGHT_CONSTANT 1365
#define ID_NEW_AFFECTOR_HEIGHT_FRACTAL  1366
#define ID_NEW_AFFECTOR_HEIGHT_TERRACE  1367
#define ID_NEW_AFFECTOR_SHADER_BITMAP   1368
#define ID_NEW_AFFECTOR_SHADER_CONSTANT 1369
#define ID_NEW_BOUNDARY_OVAL            1370
#define ID_NEW_BOUNDARY_POLYGON         1371
#define ID_NEW_BOUNDARY_RECTANGLE       1372
#define ID_NEW_FILTER_DIRECTION         1373
#define ID_NEW_FILTER_FRACTAL           1374
#define ID_NEW_FILTER_HEIGHT            1375
#define ID_NEW_FILTER_SHADER            1376
#define ID_NEW_FILTER_SLOPE             1377
#define ID_OPTIONS_FLORAPARAMETERS      1378
#define ID_OPTIONS_MAPPARAMETERS        1379
#define ID_PROMOTESHADER                1380
#define ID_REBUILD                      1381
#define ID_RECENTER                     1382
#define ID_REDRAWMAP                    1383
#define ID_REFRESH                      1384
#define ID_SELECTMODE                   1385
#define ID_STATIC                       1386
#define ID_VERIFYSHADERS                1387
#define ID_VIEWBOOKMARKS                1388
#define ID_VIEWCONSOLE                  1389
#define ID_VIEWFIND                     1390
#define ID_VIEWMAP                      1391
#define ID_VIEWPROFILE                  1392
#define ID_VIEWPROPERTIES               1393
#define ID_VIEWWARNING                  1394
#define ID_VIEW_CATALOG                 1395
#define ID_VIEW_CM                      1396
#define ID_VIEW_COLORMAP                1397
#define ID_VIEW_FLORA                   1398
#define ID_VIEW_FLORAMAP                1399
#define ID_VIEW_HEIGHTMAP               1400
#define ID_VIEW_HELP                    1401
#define ID_VIEW_HF                      1402
#define ID_VIEW_LAYERS                  1403
#define ID_VIEW_MAP_PREFERENCES         1404
#define ID_VIEW_RADIALMAP               1405
#define ID_VIEW_SHADERMAP               1406
#define ID_VIEW_SHADERS                 1407
#define ID_VIEW_WATER                   1408
#define ID_VIEW_WATERMAP                1409
#define ID_ZOOM                         1410
#define ID__INSERTINTOFLORAGROUP        1411
#define ID__INSERTINTORADIALGROUP       1412
#define ID__INSERTINTOSHADERGROUP       1413
#define IDD_DIALOG_PALETTE              1416
#define IDC_BUTTON_DELETE               1417
#define IDD_FORM_ENVIRONMENTFAMILY      1417
#define IDC_BUTTON_DELETE_ALL           1418
#define IDD_FORM_AFFECTORENVIRONMENT    1418
#define IDC_EDIT_RED                    1419
#define IDD_FORM_FRACTALFAMILY          1419
#define IDC_EDIT_GREEN                  1420
#define IDD_FORM_AFFECTORSHADERREPLACE  1420
#define IDC_EDIT_BLUE                   1421
#define IDC_EDIT_SELECTED               1422
#define IDC_BUTTON_CHANGE               1423
#define IDC_BUTTON_ADD                  1424
#define IDC_BUTTON_LOAD                 1425
#define IDC_BUTTON_SAVE                 1426
#define IDD_DIALOG_CONTROL_POINT_EDITOR 2000
#define IDD_DIALOG_CONTROL_POINT_EDIT   2001
#define IDD_FORM_AFFECTORPASSABLE       2002
#define IDD_FORM_BITMAPFAMILY           2003
#define IDD_FORM_FILTERBITMAP           2004
#define IDD_FORM_AFFECTORRIBBON         2005
#define ID_DEBUG_TEST                   3000
#define ID_VIEWENVIRONMENT              3001
#define ID_NEW_AFFECTOR_ENVIRONMENT     3002
#define ID_NEWENVIRONMENTFAMILY         3003
#define ID_VERIFYENVIRONMENTS           3004
#define ID_DELETEENVIRONMENT            3005
#define ID_VIEW_ENVIRONMENTMAP          3006
#define ID_NEWFAMILY                    3007
#define ID_VERIFYFAMILIES               3008
#define ID_DELETEFAMILY                 3009
#define ID_GROUP_FINDRULESUSINGTHISFAMILY 3010
#define ID_DEBUG_ADDALLRULES            3011
#define ID_NEW_AFFECTOR_SHADER_REPLACE  3012
#define ID_DEBUG_TESTPOINTEDITOR        3013
#define ID_BUTTON_MEDRES                3014
#define ID_BUTTON_HIGHRES               3015
#define ID_BUTTON_LOWRES                3016
#define ID_TOOLS_BAKETERRAIN            3017
#define ID_TOOLS_BAKERIVERSROADS        3018
#define ID_BUTTON_COPY_CURRENT          3019
#define ID_TOOLS_BAKEFLORA              3020
#define ID_DEBUG_VIEWBAKEDTERRAIN       3021
#define ID_EDIT_CLEARCONSOLE            3022
#define ID_BUTTON_DUMPCOLORRAMPS        3023
#define ID_NEW_AFFECTOR_PASSABLE        3024
#define ID_VIEW_PASSABLEMAP             3025
#define ID_BITMAP_PREVIEW               3026
#define ID_EDIT_BITMAP                  3027
#define ID_NEW_FILTER_BITMAP            3028
#define ID_CREATERIBBONAFFECTOR         3029
#define ID_MODIFYRIBBONAFFECTOR         3030
#define ID_BUTTON_SHOW_RIBBON           3031
#define IDC_MODIFY_MAIN                 4001
#define IDC_MODIFY_FILL                 4002
#define IDC_MODIFY_BOUNCE               4003
#define IDC_CLOUD_VELOCITY              4004
#define IDC_FOG_ENABLED                 4005
#define IDC_FOG_DENSITY                 4006
#define IDC_MODIFY_FOG                  4007
#define IDC_MODIFY_CLEAR                4008
#define IDC_CLOUD_ENABLED               4009
#define IDC_MODIFY_AMBIENT              4010
#define IDC_WINDOW_MAIN                 4011
#define IDC_WINDOW_FILL                 4012
#define IDC_WINDOW_BOUNCE               4013
#define IDC_WINDOW_FOGCOLOR             4014
#define IDC_WINDOW_CLEARCOLOR           4015
#define IDC_WINDOW_AMBIENT              4016
#define IDC_WINDOW_MAINSPECULAR         4017
#define IDC_BUTTON_GLOBALMUSIC          4017
#define IDC_EDIT_SURFACEPROPERTIES      4017
#define IDC_MODIFY_MAINSPECULAR         4018
#define IDC_EDIT_NAME                   4018
#define IDC_AMBIENTSOUNDENABLED         4019
#define IDC_SPIN_SEED                   4019
#define IDC_CHECK_FEATHERCLAMPOVERRIDE  4020
#define IDC_SLIDER_FEATHERCLAMP         4021
#define IDC_EDIT_FEATHERCLAMP           4022
#define IDC_FAMILY_SOURCE               4023
#define IDC_FAMILY_DESTINATION          4024
#define IDC_BUTTON_UP                   4025
#define IDC_BUTTON_DOWN                 4026
#define IDC_BUTTON_IMPORT_APPEND        4027
#define IDC_EDIT_Z                      4028
#define IDC_LIST_CONTROL_POINTS         4029
#define IDC_EDIT_X                      4030
#define IDC_BUTTON_IMPORT_CLEAR         4030
#define IDC_EDIT_HEIGHTVAL              4031
#define IDC_BUTTON_EDIT_CONTROL_POINT_LIST 4032
#define IDC_EDIT_HOURS                  4033
#define IDC_STATIC_TYPE                 4034
#define IDC_CHECK_LOCALGLOBALWATERTABLE 4035
#define IDC_CHECK_PASSABLE              4036
#define IDC_CHECK_FORWARDDIRECTION      4037
#define IDC_EDIT_LEGACYMAP              4038
#define IDC_CHECK_HASHEIGHTS            4039
#define IDC_CHECK_HAS_FIXED_HEIGHTS     4040
#define IDC_EDIT_WATER_SHADER           4041
#define IDC_SLIDER_FEATHER_DISTANCE_TERRAIN_SHADER 4042
#define IDC_FEATHER_DISTANCE_TERRAIN_SHADER 4043
#define IDC_FEATHER_FUNCTION_TERRAIN_SHADER 4044
#define IDC_BUTTON_WATER_SHADER_BROWSE  4045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        2003
#define _APS_NEXT_COMMAND_VALUE         3032
#define _APS_NEXT_CONTROL_VALUE         4047
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
