include library.fs_quests_sad;
include library.quests;
include library.utils;

trigger OnTheaterCreated(obj_id[] objects, obj_id player, obj_id creator)
{
	dictionary params = new dictionary();
	params.put("player", player);
	for(int i = 0; i < objects.length; i++)
	{
		messageTo(objects[i], "OnTheaterCreated", params, 0, true);
	}
	utils.setObjVar(player, fs_quests_sad.SAD_OBJVAR_MASTER_THEATER, self);
	return SCRIPT_CONTINUE;
}

messageHandler destroySelf()
{
	destroyObject(self);
	return SCRIPT_CONTINUE;
}