/**
 * Copyright (c)2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:        mission.script
 * Description:  script for mission menu options; to be attached to mission terminals
 * @author       $Author:$
 * @version      $Revision:$
 */

/***** INCLUDES ********************************************************/

include menu_info_types;

/***** INHERITS ********************************************************/

inherits terminal.base.base_terminal;

/***** CONSTANTS *******************************************************/

const string_id SID_MISSION_OPTIONS           = new string_id("terminal_ui", "mission_options");

/***** TRIGGERS ********************************************************/

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
 //int mnu = mi.addRootMenu (menu_info_types.SERVER_MISSION_OPTIONS, SID_MISSION_OPTIONS);
 int mnu = mi.addRootMenu (menu_info_types.MISSION_DETAILS, SID_MISSION_OPTIONS);
 return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
 //if ( item == menu_info_types.SERVER_MISSION_OPTIONS)
 if ( item == menu_info_types.MISSION_DETAILS)
 {
 }
 return SCRIPT_CONTINUE;
}

/***** FUNCTIONS *******************************************************/


/***** MESSAGEHANDLERS *************************************************/
