inherits creature_spawner.base_newbie_creature_spawner;

trigger OnInitialize()
{
	spawnCreatures(self);
	return SCRIPT_CONTINUE;
}

messageHandler creatureDied()
{
	doDeathRespawn(self);
	return SCRIPT_CONTINUE;
}

// overloading these two functions.			
string pickCreature()
{
	string creature = "flesh_eating_chuba";
	int choice = rand (1,3);
	switch (choice)
	{
		case 1:
			creature = "flesh_eating_chuba";
			break;
		case 2:
			creature = "capper_spineflap";
			break;
		case 3:
			creature = "diseased_nuna";
			break;
		default:
			creature = "diseased_nuna";
			break;
	}
	return creature;
}	

int getMaxPop()
{
	int maxPop = 6;
	return maxPop;
}