include library.ai_lib;
include library.hue;
include library.colors;
include library.chat;
include library.skill;

trigger OnAttach ()
{
	obj_id skirt = createObject ("object/tangible/wearables/skirt/skirt_s04.iff", self, "");
	obj_id shirt = createObject ("object/tangible/wearables/shirt/shirt_s42.iff", self, "");
	obj_id hair = createObject ("object/tangible/hair/human/hair_human_female_s07.iff", self, "");
	obj_id shoes = createObject ("object/tangible/wearables/shoes/shoes_s08.iff", self, "");
	
	setName (self, "Binna Jode");
	hue.setColor (skirt, 1, 57);
	hue.setColor (skirt, 2, 118);
	hue.setColor (shirt, 1, 118);
	hue.setColor (shirt, 2, 57);
	hue.setColor (hair, 1, 7);
	hue.setColor (shoes, 1, 57);

	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	return SCRIPT_CONTINUE;
}	

