include library.ai_lib;
include library.hue;
include library.colors;

trigger OnAttach ()
{
	obj_id shirt = createObject ("object/tangible/wearables/shirt/shirt_s07.iff", self, "");
	obj_id pants = createObject ("object/tangible/wearables/pants/pants_s12.iff", self, "");
	obj_id shoes = createObject ("object/tangible/wearables/shoes/shoes_s03.iff", self, "");
	obj_id vest  = createObject ("object/tangible/wearables/vest/vest_s05.iff", self, "");
		
	hue.setColor (shirt, 1, colors.RED);
	hue.setColor (shirt, 1, colors.YELLOW);
	hue.setColor (vest, 1, colors.BLUE);
	ai_lib.setDefaultCalmBehavior( self, ai_lib.BEHAVIOR_SENTINEL );
	setName (self, "Rakir Banai");
	return SCRIPT_CONTINUE;
}	

