#!/bin/bash

echo $*

PYTHON=c:/python20/python
COMPILER=c:/projects/swg/ep3/exe/shared/script_prep.pyc
FILES=$*

if [ -z "$1" ]; then
	FILES=`ls *.script *.scriptlib`;
fi;

for file in $FILES; do
	datafileNoExt=$(echo $file | perl -p -e 's,/dsrc/,/data/,g' | perl -p -e 's,[.]script.*,,g')
	p4 edit ${datafileNoExt}*.class | grep -v "currently opened for edit"
	${PYTHON} ${COMPILER} -dDEBUG ${file}
done

for file in $FILES; do
	datafileNoExt=$(echo $file | perl -p -e 's,/dsrc/,/data/,g' | perl -p -e 's,[.]script.*,,g')
	p4 add ${datafileNoExt}*.class | grep -v "add of existing file" | grep -v "can't add (already opened for edit)"
done
