#!/bin/bash
DATAPATH=../../../../../../../../data/sku.0/sys.server/plt.shared/loc.shared/compiled/game

FILES=$1

if [[ $1 == "" ]]; then
	FILES=`find -name "*.java"`;
fi;

javac -g -sourcepath . -classpath $DATAPATH -d $DATAPATH $FILES
