#!/bin/bash
DATAPATH=../../../../../../data/sku.0/sys.server/compiled/game

FILES=$*

if [[ $1 == "" ]]; then
	FILES=`ls *.java`;
fi;

for file in $FILES; do
	noext=$(echo $file | cut -f 1 -d .)
	p4 edit $DATAPATH/script/${noext}*.class | grep -v "currently opened for edit"
done

javac -g -sourcepath . -classpath $DATAPATH -d $DATAPATH $FILES

for file in $FILES; do
	noext=$(echo $file | cut -f 1 -d .)
	p4 add $DATAPATH/script/${noext}*.class | grep -v "add of existing file" | grep -v "can't add (already opened for edit)"
done
