include library.factions;
include library.gcw;


trigger OnAttach()
{
	setName(self, "GCW Parent Object! DO NOT DELETE");
	return SCRIPT_CONTINUE;
	
}
trigger OnInitialize()
{
	// objvars
	// intImperialControlScore
	//intRebelControlScore
	// simple to start
	setName(self, "GCW Parent Object! DO NOT DELETE");

	messageTo(self, "updateGCWData", null, 1.0f, false);

	return SCRIPT_CONTINUE;

}

messageHandler updateGCWData()
{
	setObjVar(self, "Imperial.controlScore", gcw.getImperialPercentileByRegion(self));
	setObjVar(self, "Rebel.controlScore",  gcw.getRebelPercentileByRegion(self));	
	
	messageTo(self, "updateGCWData", null, gcw.GCW_UPDATE_PULSE+rand(1, 100), false);
	return SCRIPT_CONTINUE;
}


messageHandler updateGCWScore()
{
	setObjVar(self, "Imperial.controlScore", gcw.getImperialPercentileByRegion(self));
	setObjVar(self, "Rebel.controlScore",  gcw.getRebelPercentileByRegion(self));	
	return SCRIPT_CONTINUE;
}
