include library.create;
include library.factions;
include library.utils;

inherits systems.gcw.gcw_city_kit;

void setupConstructionQuests(obj_id self, obj_id pylon)
{
	setName(pylon, "Turret Construction Site");
	
	attachScript(pylon, "systems.gcw.gcw_city_pylon_turret");
}

void setupInvasionQuests(obj_id kit)
{
}

obj_id createFactionKit(int faction, location loc)
{
	if(loc == null)
	{
		return null;
	}

	obj_id kit = null;

	if(factions.FACTION_FLAG_IMPERIAL == faction)
	{
		kit = create.object("gcw_city_imperial_turret_1", loc);
		setName(kit, "Imperial Turret");
	}
	else if(factions.FACTION_FLAG_REBEL == faction)
	{
		kit = create.object("gcw_city_rebel_turret_1", loc);
		setName(kit, "Rebel Turret");
	}

	return kit;
}
