include library.factions;
include library.gcw;
include library.utils;

inherits systems.gcw.gcw_city_kit;

obj_id getPlayerInTower()
{
	return null;
}

void putPlayerInTower()
{
}

void setupConstructionQuests(obj_id self, obj_id pylon)
{
	setName(pylon, "Tower Construction Site");
	utils.setScriptVar(pylon, "gcw.name", "Tower Construction Site");

	attachScript(pylon, "systems.gcw.gcw_city_pylon_tower");
}

void setupInvasionQuests(obj_id kit)
{
}

obj_id createFactionKit(int faction, location loc)
{
	if(loc == null)
	{
		return null;
	}

	obj_id kit = null;

	if(factions.FACTION_FLAG_IMPERIAL == faction)
	{
		kit = createObject("object/tangible/destructible/gcw_imperial_tower.iff", loc);
		setName(kit, "Imperial Watch Tower");
	}
	else if(factions.FACTION_FLAG_REBEL == faction)
	{
		kit = createObject("object/tangible/destructible/gcw_rebel_tower.iff", loc);
		setName(kit, "Rebel Watch Tower");
	}

	return kit;
}