trigger OnAttach() {

	boolean success = true;

	success &= setCraftedId(self, self);
	success &= setCrafter(self, self);

	if(success)
		detachScript(self, "item.special.serialize_component");

	return SCRIPT_CONTINUE;
}

trigger OnInitialize() {

	boolean success = true;

	success &= setCraftedId(self, self);
	success &= setCrafter(self, self);

	if(success)
		detachScript(self, "item.special.serialize_component");

	return SCRIPT_CONTINUE;
}