include library.ai_lib;
inherits theme_park.poi.base;

trigger OnAttach ()
{
	string objective = poiGetObjective (self);
	if ( objective == "tuskens")
	{
		obj_id tr1 = poiCreateNpc ("tusken", -1, -2 );
		obj_id tr2 = poiCreateNpc ("tusken", 1, 1 );
		obj_id tr3 = poiCreateNpc ("tusken", 1, 3 );
		attachScript (tr2, "theme_park.poi.tatooine.behavior.tusken_stationary_poi");
		attachScript (tr3, "theme_park.poi.tatooine.behavior.tusken_stationary_poi");
		string[] patrolPoints = new string[ 4 ];
		patrolPoints[0] = "10, 10";
		patrolPoints[1] = "10, -10.3";
		patrolPoints[2] = "-10, -10";
		patrolPoints[3] = "-10, 10";
		setPatrolPath (tr1, patrolPoints);
		location here = getLocation (self);
		obj_id fire = poiCreateObject ( self, "campfire", "object/static/particle/particle_campfire_style_1.iff", 1, 2 );
		obj_id center = poiCreateObject ( self, "center", "object/tangible/camp/campfire_logs_burnt.iff", 1, 2 );
		return SCRIPT_CONTINUE;
	}
return SCRIPT_CONTINUE;
}

void setPatrolPath (obj_id npc, string[] patrolPoints )
{	
	ai_lib.setPatrolPath( npc, patrolPoints );
	return;
}

	