include library.ai_lib;
include library.create;

inherits city.interior_convo_base;

trigger OnInitialize()
{
	spawnGuyOne( self );
	spawnGuyTwo( self );
	
	messageTo( self, "checkForScripts", null, 5, false );
	messageTo( self, "handleChatting", null, 10, false );
	return SCRIPT_CONTINUE;
}

messageHandler handleChatting()
{
	obj_id guy1 = getObjIdObjVar( self, "guy1" );
	obj_id guy2 = getObjIdObjVar( self, "guy2" );

	if ( !exists(guy1) || !exists(guy2) )
		return SCRIPT_CONTINUE;

	faceTo (guy1, guy2);
	faceTo (guy2, guy1);
	setAnimationMood (guy1, "conversation");
	setAnimationMood (guy2, "conversation");

	return SCRIPT_CONTINUE;
}

messageHandler handleGuyOneKilled()
{
	spawnGuyOne( self );
	return SCRIPT_CONTINUE;
}

messageHandler handleGuyTwoKilled()
{
	spawnGuyTwo( self );
	return SCRIPT_CONTINUE;
}

messageHandler checkForScripts()
{
	if (hasScript (self, "theme_park.poi.launch"))
	{
		detachScript (self, "theme_park.poi.launch");
	}		
	return SCRIPT_CONTINUE;
}