include library.attrib;
include library.groundquests;

const boolean LOGGING_ON			= true; 
const string SCRIPT_LOG				= "outbreak_pathing";

const string TRIGGER_NAME_PREFIX 		= "camp_arrival_trigger_";
const string UPDATE_SIGNAL			= "update_signal";
const float TRIGGER_RADIUS 			= 40f;

trigger OnInitialize()
{
	//on init add trig volume
	setAttributeInterested(self, attrib.OUTBREAK_SURVIVOR);
	createTriggerVolume(TRIGGER_NAME_PREFIX + self, TRIGGER_RADIUS, true);
	return SCRIPT_CONTINUE;
}

trigger OnTriggerVolumeEntered(string volumeName, obj_id whoTriggeredMe)
{
	blog("OnTriggerVolumeEntered INIT: "+whoTriggeredMe);

	if(isPlayer(whoTriggeredMe))
		return SCRIPT_CONTINUE;

	messageTo(whoTriggeredMe, "cleanUpCampNpcAndParent", null, 1, false);
	return SCRIPT_CONTINUE;		
}

trigger OnTriggerVolumeExited(string volumeName, obj_id whoTriggeredMe)
{
	blog("Exited trigger volume: "+whoTriggeredMe);
	return SCRIPT_CONTINUE;
}

boolean blog(string msg)
{
	if(LOGGING_ON)
		LOG(SCRIPT_LOG,msg);
	return true;
}
