
trigger OnAttach()
{
	messageTo(self, "removeConversationScripts", null, 10, false);
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	messageTo(self, "removeConversationScripts", null, 10, false);
	return SCRIPT_CONTINUE;
}

messageHandler removeConversationScripts()
{
	if(hasScript(self, "npc.faction_recruiter.recruiter_setup"))
	{
		detachScript(self, "npc.faction_recruiter.recruiter_setup");
	}
	return SCRIPT_CONTINUE;	
}