include library.ai_lib;
include ai.ai_combat;
include library.utils;
include library.attrib;

//This script will make the rancor and slave fight.

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)

{
if (isPlayer (item))

	{
		obj_id rancor = getObjIdObjVar (self, "rancor");
		obj_id slave = getObjIdObjVar (self, "slave");
		startCombat (rancor, slave);
		return SCRIPT_CONTINUE;
	}
	
return SCRIPT_CONTINUE;
}