include library.ai_lib;
include library.combat;
include library.utils;
include library.create;

//This script will spawn the Nightsister Protectors when Axkva Min (the boss) is attacked.

messageHandler spawnguards ()
{
	obj_id axkva = params.getObjId("axkva");
	
	//debugSpeakMsg(axkva, "Message Received");
	
	string datatable = "datatables/spawning/theme_park/dathomir_nsister_rancor_cave_guards.iff";
	
	if ( datatable == null )
	{
		//debugSpeakMsg (axkva, "I have no string table");
		return SCRIPT_OVERRIDE;
	}		
	
	int numberOfCreaturesToSpawn = dataTableGetNumRows (datatable);
	int x = utils.getIntScriptVar (self, "guardCounter");
	
	//debugSpeakMsg(axkva, "Rows: " + numberOfCreaturesToSpawn + " -- X: " + x);
	
	while (x < numberOfCreaturesToSpawn)
	{
		string spawn = dataTableGetString (datatable, x, "spawns");

		float xCoord = dataTableGetFloat (datatable, x, "loc_x");
		float yCoord = dataTableGetFloat (datatable, x, "loc_y");
		float zCoord = dataTableGetFloat (datatable, x, "loc_z");

		location myself = getLocation (self);
		string planet = myself.area;

		string spawnRoom = dataTableGetString (datatable, x, "room");
		obj_id room = getCellId (self, spawnRoom);

		location spawnPoint = new location (xCoord, yCoord, zCoord, planet, room);

		obj_id spawnedCreature = create.object (spawn, spawnPoint);
		
		//if(!isIdValid(spawnedCreature)) debugSpeakMsg(axkva, "Bad spawn");
		
		setObjVar (spawnedCreature, "cave", self);

		string geoScript = dataTableGetString (datatable, x, "script");
		
		ai_lib.setDefaultCalmBehavior(self, ai_lib.BEHAVIOR_SENTINEL);

		if (geoScript != null && geoScript != "")
		{

			attachScript (spawnedCreature, geoScript);
		}

		string creatureName = dataTableGetString (datatable, x, "name");

		if (creatureName != null && creatureName != "")
		{
			setName (spawnedCreature, creatureName);
		}
		
		string mood = dataTableGetString (datatable, x, "mood");
		float yaw = dataTableGetFloat (datatable, x, "yaw");
		
		setYaw (spawnedCreature, yaw);
		ai_lib.setDefaultCalmMood (spawnedCreature, mood);
		
		setObjVar (spawnedCreature, "spawn_number", x);

		x = x + 1;
		utils.setScriptVar (self, "guardCounter", x);

		messageTo ( self, "beginSpawn", null, 1, false );
	}		
	
	return SCRIPT_CONTINUE;
}