/**********************************************************************
 * Copyright (c)2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:        hospital_heal
 * Description:  allows the slow healing of wounds and shock for all within
 *		 the building.
 * @author       $Author:$
 * @version      $Revision:$
 **********************************************************************/


/***** INCLUDES ********************************************************/
include library.healing;
include library.structure;
include library.player_structure;
include library.utils;

/***** CONSTANTS *******************************************************/
const int HEALING_PULSE_MIN	= 200;
const int HEALING_PULSE_MAX	= 400;
const int WOUND_HEAL		= 10;
const int SHOCK_HEAL		= 3 ;


/***** TRIGGERS ********************************************************/
trigger OnAttach()
{
	if ( player_structure.isCivic( self ) )
	{
		if (!utils.hasScriptVar(self, "terminalsCreated" ))
		{
			structure.createStructureTerminals( self, "datatables/structure/municipal/registration_terminal.iff" );
			utils.setScriptVar(self, "terminalsCreated",true );
		}
	}
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	if (!utils.hasScriptVar(self, "terminalsCreated" ))
	{
		structure.createStructureTerminals( self, "datatables/structure/municipal/registration_terminal.iff" );
		utils.setScriptVar(self, "terminalsCreated",true );
	}
	return SCRIPT_CONTINUE;
}

/***** MESSAGEHANDLERS *************************************************/

/***** COMMANDHANDLERS *************************************************/


/***** FUNCTIONS *******************************************************/
