include library.utils;
include library.sui;
include library.pet_lib;

trigger OnAttach ()
{
	setName (self, "Art Crate");
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuRequest (obj_id player, menu_info mi)
{
	menu_info_data mid = mi.getMenuItemByType(menu_info_types.ITEM_USE);
	if ( mid == null )
	{
		return SCRIPT_CONTINUE;
	}

	mid.setServerNotify(true);

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect (obj_id player, int item)
{
	if ( item == menu_info_types.ITEM_USE )
	{
		makeArt(self, player);
	}

	return SCRIPT_CONTINUE;
}

void makeArt (obj_id self, obj_id player)
{
	obj_id inv = utils.getInventoryContainer (player);

	int whichArt = rand (1,3);

	if (whichArt == 1)
	{
		createObject ("object/tangible/furniture/all/frn_all_decorative_sm_s4.iff", inv, null);
	}

	if (whichArt == 2)
	{
		createObject ("object/tangible/furniture/all/frn_all_decorative_lg_s1.iff", inv, null);
	}

	else
	{
		createObject ("object/tangible/furniture/all/frn_all_decorative_lg_s2.iff", inv, null);
	}
	destroyObject (self);
	return;
}
