trigger OnAttach ()
{
	messageTo (self, "doubleCheck", null, 3600, false );
	return SCRIPT_CONTINUE;
}

trigger OnDeath (obj_id killer, obj_id corpse)
{
	obj_id top = getTopMostContainer (self);
	if (isIdValid (top))
	{
		string name = getTemplateName (top);
		if (name == "object/building/general/bunker_allum_mine.iff")
		{
			CustomerServiceLog ("DUNGEON_DeathWatchBunker", "* Death Watch Player Died: %TU has died in the Death Watch Hideout.", self);
			detachScript (self, "theme_park.dungeon.death_watch_bunker.death_script");
		}
	}
	return SCRIPT_CONTINUE;
}

messageHandler doubleCheck ()
{
	obj_id top = getTopMostContainer (self);
	if (isIdValid (top))
	{
		string name = getTemplateName (top);
		if (name == "object/building/general/bunker_allum_mine.iff")
		{
			messageTo (self, "doubleCheck", null, 3600, false );
			return SCRIPT_CONTINUE;
		}
		else
		{
			detachScript (self, "theme_park.dungeon.death_watch_bunker.death_script");
			return SCRIPT_CONTINUE;
		}
	}
	else
	{
		detachScript (self, "theme_park.dungeon.death_watch_bunker.death_script");
	}

	return SCRIPT_CONTINUE;
}