include library.instance;

trigger OnObjectMenuRequest(obj_id player, menu_info item)
{
	item.addRootMenu(menu_info_types.ITEM_USE, new string_id("building_name", "heroic_exar_enter"));

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if ( item == menu_info_types.ITEM_USE)
	{

		if (getDistance(player, self) > 6.0f)
		{
			CustomerServiceLog("instance-heroic_exar_kun", "Player successfully used the door but server placed them "+getDistance(player, self)+"m away");
		}

		if ( instance.isFlaggedForInstance(player, "heroic_exar_kun") )
		{
			instance.requestInstanceMovement(player, "heroic_exar_kun");
		}
		else
		{
			string chance = "" + rand(1,5);
			if ( rand(0,999) == 999 )
			{
				chance = "rare";
			}

			sendSystemMessage(player, new string_id("building_name", "heroic_exar_unflagged_entrance_"+chance));
		}
		return SCRIPT_CONTINUE;
	}

	return SCRIPT_CONTINUE;
}
