include library.trial;

trigger OnAttach()
{
	setCreatureCoverVisibility(self, false);
	setInvulnerable(self, true);
	aiEquipPrimaryWeapon(self);
	return SCRIPT_CONTINUE;
}

messageHandler kill_command()
{
	trial.setHp(self, 415245);
	obj_id[] players = trial.getValidTargetsInCell(trial.getTop(self), "r7");
	obj_id closest = trial.getClosest(self, players);
	startCombat(self, closest);
	return SCRIPT_CONTINUE;
}