include library.ai_lib;
include library.create;

trigger OnInitialize ()
{
	obj_id guy = spawnGuyOne( self );
	obj_id guy2 = spawnGuyTwo( self );
	spawnDroid();
	faceTo (guy, guy2);
	messageTo( self, "handleChatting", null, 10.0f, false );
	messageTo( self, "checkForScripts", null, 10, true );
	return SCRIPT_CONTINUE;
}

obj_id spawnGuyOne(obj_id baseObject)
{
	location here = getLocation (baseObject);
	here.x = here.x + 1;
	obj_id guy1 = create.object("commoner", here);
	setObjVar( baseObject, "guy1", guy1);
	return guy1;
}
obj_id spawnGuyTwo(obj_id baseObject)
{
	location here = getLocation (baseObject);
	here.x = here.x - 1;
	obj_id guy2 = create.object("commoner", here);
	setObjVar( baseObject, "guy2", guy2 );
	return guy2;
}
void spawnDroid()
{
	location here = getLocation (getSelf());
	here.z = here.z + 1;
	string droidToSpawn = getRandomDroid();
	obj_id droid = create.object (droidToSpawn, here);
	ai_lib.setDefaultCalmBehavior( droid, ai_lib.BEHAVIOR_SENTINEL );
}

messageHandler handleDeadGuyOne()
{
	spawnGuyOne( self );
	return SCRIPT_CONTINUE;
}

messageHandler handleDeadGuyTwo()
{
	spawnGuyTwo( self );
	return SCRIPT_CONTINUE;
}

messageHandler handleDeadDroid()
{
	spawnDroid();
	return SCRIPT_CONTINUE;
}

messageHandler handleChatting()
{
	messageTo( self, "handleChatting", null, 600, false );
	obj_id guy1 = getObjIdObjVar( self, "guy1" );
	obj_id guy2 = getObjIdObjVar( self, "guy2" );
	if ( !exists( guy1) || !exists(guy2) )
		return SCRIPT_CONTINUE;

	faceTo (guy1, guy2);
	faceTo (guy2, guy1);
	setAnimationMood (guy1, "conversation");
	setAnimationMood (guy2, "conversation");
	return SCRIPT_CONTINUE;
}

string getRandomDroid()
{
	int dnum = rand( 2,5 );
	string droid = "r"+dnum;
	return droid;
}

messageHandler checkForScripts()
{
	if (hasScript (self, "theme_park.poi.launch"))
	{
		detachScript (self, "theme_park.poi.launch");
	}		
	return SCRIPT_CONTINUE;
}