include library.ai_lib;
include library.create;

trigger OnAttach ()
{
	return SCRIPT_CONTINUE;
	/*
	spawnMusician( self );
	messageTo( self, "handlePlaying", null, 10, true );
	messageTo( self, "checkForScripts", null, 10, true );
	return SCRIPT_CONTINUE;
	*/
}

messageHandler handlePlaying()
{
	messageTo( self, "handlePlaying", null, 600, true );
	obj_id musician = getObjIdObjVar( self, "musician" );
	if ( !exists( musician) )
		return SCRIPT_CONTINUE;

	setAnimationMood (musician, "whatever");
	return SCRIPT_CONTINUE;
}

void spawnMusician( obj_id baseObject )
{
	obj_id musician = create.themeParkObject( "noble", 1f, 0f, "objectDestroyed", 0f );
	createObject ("object/tangible/instrument/kloo_horn.iff", musician, "");
	setObjVar( baseObject, "musician", musician );
}

messageHandler objectDestroyed ()
{
	spawnMusician( self );
	return SCRIPT_CONTINUE;
}

messageHandler checkForScripts()
{
	if (hasScript (self, "theme_park.poi.launch"))
	{
		detachScript (self, "theme_park.poi.launch");
	}		
	return SCRIPT_CONTINUE;
}