include library.utils;

trigger OnAttach()
{
	setScale(self, 1.5f);
	createTriggerVolume("playerEnter", 28f, true);
	return SCRIPT_CONTINUE;
}
trigger OnIncapacitated(obj_id player)
{
	messageTo(self, "destroyCorpse", null, 5.0f, true);
	return SCRIPT_CONTINUE;
}

trigger OnDestroy()
{
	obj_id player = getObjIdObjVar(self, "player");
	int number = getIntObjVar(self, "demoNumber");
	if (number == 1)
		messageTo(player, "resetDemo1", null, 1.0f, true);
	if (number == 2)
		messageTo(player, "resetDemo2", null, 1.0f, true);
	return SCRIPT_CONTINUE;
}

messageHandler destroyCorpse()
{
	destroyObject(self);
	return SCRIPT_CONTINUE;
}



trigger OnTriggerVolumeEntered(string volumeName, obj_id breacher)
{

	if ( volumeName == "playerEnter" )
	{
		if(!utils.hasScriptVar(self, "intBreached"))
		{
			debugSpeakMsg(self, "Berece");
			if(isPlayer(breacher))
			{
				startCombat(self, breacher);

				utils.setScriptVar(self, "intBreached", 1);
				setState(self, STATE_COMBAT, true);
			}
		}

	}
	return SCRIPT_CONTINUE;
}

