//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UiBuilder.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_UIBUILTYPE                  129
#define IDD_SAVE_AS_TEMPLATE            130
#define IDD_OBJECTBROWSERDIALOG         131
#define IDR_IMAGELIST                   136
#define IDC_MULTIDROP                   137
#define IDR_CONTEXTMENU                 142
#define IDD_DEFAULTPROPERTIES           143
#define IDI_ADDPROPERTY                 144
#define IDI_REMOVEPROPERTY              145
#define IDD_ADDPROPERTY                 146
#define IDD_BASEPROPERTIES_PAGE         151
#define IDD_PROPERTIES_PAGE             152
#define IDD_PROPERTY_DIALOG             153
#define IDD_STRING_PROPERTY_DIALOG      154
#define IDD_VECTOR2_PROPERTY_DIALOG     157
#define IDC_GRABHAND                    163
#define IDI_ALIGNBOTTOM                 164
#define IDI_ALIGNTOP                    165
#define IDI_ALIGNLEFT                   166
#define IDI_ALIGNRIGHT                  167
#define IDD_IMPORTIMAGE                 169
#define IDD_PROGRESS                    170
#define IDI_FOLDER                      171
#define IDI_VIEWIMAGE                   172
#define IDD_PAGEFILE                    173
#define IDI_ALIGNHCENTER                174
#define IDI_ALIGNVCENTER                175
#define IDD_OBJECTPROPERTIESDIALOG      176
#define IDR_PROPERTYCONTEXTMENU         178
#define IDD_SELECTREGION                179
#define IDI_ZOOMOUT                     181
#define IDI_DRAWHIGHLIGHT               182
#define IDI_ZOOMIN                      183
#define ID_SAVE_NEXT_VERSION            1000
#define IDC_OBJECTSTRUCTURE             1001
#define IDC_PROPERTYLIST                1002
#define IDC_OBJECTTYPE                  1003
#define IDC_ADDPROPERTY                 1004
#define IDC_REMOVEPROPERTY              1005
#define IDC_PROPERTYNAME                1006
#define IDC_PROPERTYVALUE               1007
#define IDC_PROPERTY_NAME               1008
#define IDC_STRING_PROPERTY             1010
#define IDC_OBJECTPROPERTIES            1011
#define IDC_YMINUS10                    1017
#define IDC_YMINUS1                     1018
#define IDC_YPLUS1                      1019
#define IDC_YPLUS10                     1020
#define IDC_XPLUS1                      1021
#define IDC_XPLUS10                     1022
#define IDC_XMINUS10                    1023
#define IDC_XMINUS1                     1024
#define IDC_TILEMAX                     1063
#define IDC_NUMFRAGMENTS                1065
#define IDC_SOURCEFILE                  1066
#define IDC_LARGESTFRAGMENT             1067
#define IDC_SMALLESTFRAGMENT            1068
#define IDC_TOTALMEMORY                 1069
#define IDC_MEMORYWASTED                1070
#define IDC_TILEMIN                     1071
#define IDC_BROWSESOURCE                1072
#define IDC_USEWHOLEIMAGE               1073
#define IDC_USESUBIMAGE                 1074
#define IDC_SUBIMAGERECT                1075
#define IDC_VIEWIMAGE                   1076
#define IDC_GENERATEFRAGMENTS           1077
#define IDC_COMPRESSFRAGMENTS           1078
#define IDC_COMPRESSIONFORMAT           1080
#define IDC_PROGRESS                    1100
#define IDC_STATUS                      1101
#define IDC_PARENT                      1102
#define IDC_NEWFILE                     1103
#define IDC_PAGEFILE                    1104
#define IDC_CANVAS                      1106
#define IDC_VALUELABEL                  1107
#define IDC_VALUE                       1108
#define IDC_DRAWHIGHLIGHT               1110
#define IDC_ZOOMIN                      1112
#define IDC_ZOOMOUT                     1113
#define IDC_ZOOMLEVEL                   1114
#define ID_FILE_IMPORT                  32771
#define ID_FILE_EXPORT                  32772
#define ID_FILE_SAVEAS                  32774
#define ID_FILE_RECENTFILES_EMPTY       32775
#define IDC_RENAMEOBJECT                32776
#define IDC_SHOWOBJECT                  32777
#define ID_INSERT_NAMESPACE             32778
#define ID_INSERT_DATASOURCECONTAINER   32779
#define ID_INSERT_DATASOURCE            32780
#define ID_INSERT_DATAITEM              32781
#define ID_INSERT_CLOCK                 32782
#define ID_INSERT_CURSOR                32783
#define ID_INSERT_IMAGEFRAME            32784
#define ID_INSERT_TEMPLATE              32785
#define ID_INSERT_APPLICATIONOBJECT     32786
#define ID_INSERT_PAGE                  32787
#define ID_INSERT_COMPOSITE             32788
#define ID_INSERT_TABBEDPANE            32789
#define ID_INSERT_VOLUMEPAGE            32790
#define ID_INSERT_TABLE                 32791
#define ID_INSERT_STATICTEXT            32792
#define ID_INSERT_ELLIPSE               32793
#define ID_INSERT_IMAGE                 32794
#define ID_INSERT_PIE                   32795
#define ID_INSERT_RUNNER                32796
#define ID_INSERT_BUTTON                32797
#define ID_INSERT_CHECKBOX              32798
#define ID_INSERT_GRID                  32799
#define ID_INSERT_PROGRESSBAR           32800
#define ID_INSERT_SCROLLBAR             32801
#define ID_INSERT_SLIDERBAR             32802
#define ID_INSERT_SLIDERPLANE           32803
#define ID_INSERT_TEXTBOX               32804
#define ID_INSERT_COMBOBOX              32805
#define ID_INSERT_LIST                  32806
#define ID_INSERT_TREEVIEW              32807
#define ID_INSERT_POPUPMENU             32808
#define ID_INSERT_RADIALMENU            32809
#define ID_INSERT_CURSORSET             32810
#define ID_INSERT_TABLEMODELDEFAULT     32811
#define ID_INSERT_TABLEHEADER           32812
#define ID_INSERT_STYLE_BUTTON          32813
#define ID_INSERT_STYLE_CHECKBOX        32814
#define ID_INSERT_STYLE_DROPDOWNBOX     32815
#define ID_INSERT_STYLE_IMAGE           32816
#define ID_INSERT_STYLE_GRID            32817
#define ID_INSERT_STYLE_LISTBOX         32818
#define ID_INSERT_STYLE_PROGRESSBAR     32819
#define ID_INSERT_STYLE_SLIDERBAR       32820
#define ID_INSERT_STYLE_TEXT            32821
#define ID_INSERT_STYLE_TEXTBOX         32822
#define ID_INSERT_STYLE_TOOLTIP         32823
#define ID_INSERT_STYLE_TABSET          32824
#define ID_INSERT_STYLE_TABBEDPANE      32825
#define ID_INSERT_STYLE_RECTANGLE       32826
#define ID_INSERT_STYLE_POPUPMENU       32827
#define ID_INSERT_STYLE_RADIALMENU      32828
#define ID_INSERT_STYLE_LIST            32829
#define ID_INSERT_STYLE_TREEVIEW        32830
#define ID_INSERT_STYLE_PIE             32831
#define ID_INSERT_STYLE_PALETTE         32832
#define ID_INSERT_EFFECTOR_COLOR        32833
#define ID_INSERT_EFFECTOR_OPACITY      32834
#define ID_INSERT_EFFECTOR_LOCATION     32835
#define ID_INSERT_EFFECTOR_SIZE         32836
#define ID_INSERT_EFFECTOR_ROTATION     32837
#define ID_INSERT_DEFORMER_HUD          32838
#define ID_INSERT_DEFORMER_WAVE         32839
#define ID_INSERT_DEFORMER_ROTATE       32840
#define ID_INSERT_DROPDOWNBOX           32841
#define ID_INSERT_LISTBOX               32842
#define ID_INSERT_TABSET                32843
#define ID_VIEW_RUN                     32900
#define ID_VIEW_CURSOR                  32901
#define ID_VIEW_HIGHLIGHT               32902
#define ID_VIEW_GRID                    32903
#define ID_VIEW_SHOWSHADERS             32904
#define ID_VIEW_GRIDSETTINGS            32905
#define ID_VIEW_HIGHLIGHTSETTINGS       32906
#define ID_VIEW_DEFAULT_PROPERTIES      32907
#define ID_SELECTION_BURROW             32908
#define ID_SELECTION_CLEARALL           32909
#define ID_SELECTION_DESCENDANTS        32910
#define ID_SELECTION_ANCESTORS          32912
#define ID_EDIT_CANCELDRAG              32913
#define IDC_COLLAPSEALL                 32914
#define IDC_COLLAPSE                    32915
#define IDC_FULLYEXPAND                 32917
#define IDC_CLEARCOLLAPSEALL            32918
#define ID_SELECTION_DELETE             32919
#define IDC_HIDEOBJECT                  32920
#define IDC_SHOWTOPLEVELPAGE            32921
#define ID_SELECTION_ALIGNTOP           32922
#define ID_TOGGLE_GRID                  32923
#define ID_SELECTION_ALIGNLEFT          32924
#define ID_SELECTION_ALIGNBOTTOM        32925
#define ID_SELECTION_ALIGNRIGHT         32926
#define ID_SELECTION_ALIGNCENTERX       32927
#define ID_SELECTION_ALIGNCENTERY       32928
#define ID_SELECTION_ALIGNWIDTH         32929
#define ID_SELECTION_ALIGNHEIGHT        32930
#define IDC_CHECKOUT                    32931
#define ID_VIEW_SELECTIONPROPERTIES     32932
#define ID_VIEW_OBJECTBROWSER           32933
#define ID_FOLLOWLINK                   32934
#define ID_EDITPROPERTY                 32935

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32936
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
