include library.utils;

const string_id TELEPORT					= new string_id("dungeon/myyydril", "teleport");

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	if ( !utils.isNestedWithin(self, player) )
		return SCRIPT_CONTINUE;

	int teleport = mi.addRootMenu(menu_info_types.SERVER_MENU1, TELEPORT);

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if ( !utils.isNestedWithin(self, player) )
			return SCRIPT_CONTINUE;

	if ( item == menu_info_types.SERVER_MENU1 )
	{
		obj_id container = getTopMostContainer(self);
		string template = "";
		if (isIdValid(container))
			template = getTemplateName(container);
		else
			return SCRIPT_CONTINUE;

		if (template.equals("object/building/kashyyyk/thm_kash_myyydril_caverns.iff"))
		{
			//sendSystemMessageTestingOnly(player, "Fooooooooom!  Whooooooooosh!");
			warpPlayer(player, "kashyyyk_main", -568, 0, -100 , null, 0, 0, 0, null, false);
		}
		else
		{
			string_id msg = new string_id("dungeon/myyydril", "cantusestone");
			sendSystemMessage(player, msg);
		}
	}

	return SCRIPT_CONTINUE;
}