/**
 * mount_test.script
 */

trigger OnHearSpeech(obj_id objSpeaker, string strText)
{
	if (strText == "mounttest")
	{
		boolean mpmResult = makePetMountable(self);
		updateMountWearableVisuals(self);

		boolean mcResult = mountCreature(objSpeaker, self);
		dismountCreature(objSpeaker);

		obj_id mountId = getMountId(objSpeaker);
		int canMakePetMountable = couldPetBeMadeMountable(self);
	}

	return SCRIPT_CONTINUE;
}
