/**
 * scale_test.script
 */

trigger OnHearSpeech(obj_id objSpeaker, string strText)
{
	if (strText == "scaletest")
	{
		float bothanDefaultScale = getDefaultScaleFromObjectTemplate("object/creature/player/bothan_male.iff");
		LOG("scaletest", "bothan default scale: " + Float.toString(bothanDefaultScale));

		float humanDefaultScale  = getDefaultScaleFromObjectTemplate("object/creature/player/human_male.iff");
		LOG("scaletest", "human default scale: " + Float.toString(humanDefaultScale));

		float wookieeDefaultScale= getDefaultScaleFromObjectTemplate("object/creature/player/wookiee_male.iff");
		LOG("scaletest", "wookiee default scale: " + Float.toString(wookieeDefaultScale));
	}

	return SCRIPT_CONTINUE;
}
