include library.utils;
include library.space_dungeon;
include library.npe;

#ifdef DEBUG

trigger OnSpeaking(string text)
{
	java.util.StringTokenizer st = new java.util.StringTokenizer(text);
	string arg = st.nextToken();

	if (arg.equals("testing"))
	{
		sendSystemMessageTestingOnly(self, "1... 2... 3...");
	}
	
	if (arg.equals("path"))
	{
		float x = Float.parseFloat(st.nextToken());
		float y = Float.parseFloat(st.nextToken());
		float z = Float.parseFloat(st.nextToken());
		location destination = new location(x, y, z);
		createClientPathAdvanced(self, getLocation(self), destination, "default");
	}


	return SCRIPT_CONTINUE;
}

#endif
