inherits theme_park.newbie_tutorial.tutorial_base;

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{

	//sysMessage( player, "mission_terminal" );
//	playMusic( player, "sound/tut_00_mission_terminal.snd" );

	obj_id missionNpc = getObjIdObjVar( getTopMostContainer( self ), MISSION_NPC );
	if ( missionNpc != null )
		messageTo( missionNpc, "handleYellAtNewbie", null, 1, false );

	return SCRIPT_OVERRIDE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	return SCRIPT_OVERRIDE;
}

