include library.ai_lib;
include library.chat;

inherits theme_park.newbie_tutorial.tutorial_base;

trigger OnAttach()
{
	messageTo( self, "handleSpamming", null, rand(30,60), false );
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	chat.chat( self, new string_id ( NEWBIE_CONVO, "nervous_guy" + rand(1,5) ));
	return SCRIPT_CONTINUE;
}

messageHandler handleSpamming()
{
	obj_id player = getPlayer( self );
	if ( hasObjVar( player, "newbie.killedPirate" ) )
		return SCRIPT_CONTINUE;

	if ( (rand(1,10)==1) && (isInRoom( player, "r7" )) )
	{
		chat.chat( self, new string_id ( NEWBIE_CONVO, "nervous_guy" + rand(1,5) ));
	}

	messageTo( self, "handleSpamming", null, rand(30,60), false );

	return SCRIPT_CONTINUE;
}
