include library.utils;

inherits theme_park.newbie_tutorial.tutorial_base;

trigger OnAttach()
{
	newbieTutorialRequest(self, "clientReady");
	return SCRIPT_CONTINUE;
}

trigger OnNewbieTutorialResponse( string action )
{
	if ( action == "clientReady" )
	{
		sendStartingMessageToPlayer( self );
		getStartLocationWaypoint( self );

		removeObjVar( self, "newbie" );
		removeObjVar( self, "skipTutorial" );
		removeObjVar( self, "banking_bankid" );

		attachScript( self, "holocron.newbie_handoff" );
		detachScript( self, NEWBIE_SCRIPT_EMAIL );
		return SCRIPT_CONTINUE;
	}
	return SCRIPT_CONTINUE;
}

void getStartLocationWaypoint( obj_id player )
{
	obj_id wayp = createWaypointInDatapad( player, getLocation( player ) );
	if (isIdValid(wayp))
	{
		setWaypointName( wayp, getString( STARTLOC_NAME ) );
		setWaypointActive( wayp, false );
		setWaypointVisible( wayp, true );
	}
}

