include library.chat;

inherits theme_park.newbie_tutorial.tutorial_base;

messageHandler initiateConvo()
{
	obj_id player = getPlayer( self );
	if ( player != null )
		faceToBehavior( self, player );

	doAnimationAction( self, "wave_hail" );
	chat.chat( self, new string_id ( NEWBIE_CONVO, "off_1_greeting" ));
	return SCRIPT_CONTINUE;
}
trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	removeStaticWaypoint( self );
	int mnu = mi.addRootMenu (menu_info_types.CONVERSE_START, null);
	menu_info_data mdata = mi.getMenuItemById(mnu);
	mdata.setServerNotify(false);
	return SCRIPT_CONTINUE;
}

trigger OnStartNpcConversation (obj_id speaker)
{

	faceToBehavior( self, speaker );
	string_id greeting = new string_id (NEWBIE_CONVO, "off_1_start");//How ya doin?
	string_id response[] = new string_id [2];
	response[0] = new string_id (NEWBIE_CONVO, "off_1_reply_1");//Could be better
	response[1] = new string_id (NEWBIE_CONVO, "off_1_reply_2");//combat is not my thing

	npcStartConversation (speaker, self, CONVO, greeting, response);

	return SCRIPT_CONTINUE;
}

trigger OnNpcConversationResponse(string convo, obj_id player, string_id response)
{
	npcRemoveConversationResponse(player, response );

	if ( response.getAsciiId().equals("off_1_reply_1"))//combat aint my thing
	{
		string_id message = new string_id (NEWBIE_CONVO, "off_1_gotrain");//go train
		npcSpeak( player, message );
		doAnimationAction( self, "point_right" );
		npcEndConversation( player );
	}
	else if ( response.getAsciiId().equals("off_1_reply_2"))//I'd be better with training
	{
		doAnimationAction( self, "laugh_pointing" );
		string_id message = new string_id (NEWBIE_CONVO, "off_1_gotrain2");//go train
		npcSpeak( player, message );
		npcEndConversation( player );
	}

	return SCRIPT_CONTINUE;
}

trigger OnEndNpcConversation(obj_id player)
{
	obj_id trainer = getObjIdObjVar( getTopMostContainer( self ), TRAINER );
	faceToBehavior( trainer, player );

	makeStaticWaypoint( trainer );

	chat.chat( trainer, new string_id (NEWBIE_CONVO, "trainer_grunt") );
	return SCRIPT_CONTINUE;
}

