/**
 * Copyright (c) ©2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:        camp_improved.script
 * Description:  camp_improved
 * @author       $Author:$
 * @version      $Revision: #1 $
 */

//------------------------------------------------
// Inherits
//------------------------------------------------

inherits item.camp.camp_base;

//------------------------------------------------
// Methods
//------------------------------------------------

//------------------------------------------------
// OnAttach
//------------------------------------------------

trigger OnAttach()
{
	// Set our skill req.
	setObjVar( self, "campPower", 3 );
	setObjVar( self, "skillReq", 30 );

	return SCRIPT_CONTINUE;
}
