include library.structure;

trigger OnAttach()
{
	messageTo(self, "handleInitializeCloningTube", null, 3.0f, false);

	return SCRIPT_CONTINUE;
}

messageHandler handleInitializeCloningTube()
{
	attachScript(self, "structure.municipal.cloning_facility");
	string myTemplate = getTemplateName(self);
	dictionary facilityData = dataTableGetRow(structure.DATATABLE_CLONING_FACILITY_RESPAWN, myTemplate);
	dictionary dict = new dictionary();
	dict.put("facilityData", facilityData);

	messageTo(self, "registerCloningFacility", dict, 10.0f, false);

	return SCRIPT_CONTINUE;
}

