include library.travel;

trigger OnAttach()
{
	messageTo(self, "handleInitializeShuttleBeacon", null, 3.0f, false);

	return SCRIPT_CONTINUE;
}

messageHandler handleInitializeShuttleBeacon()
{
	obj_id parent = getObjIdObjVar(self, "theater.parent");

	if(!isIdValid(parent))
		return SCRIPT_CONTINUE;

	string name = getName(parent);
	//int cost = (int)getFloatObjVar(parent, "modules.shuttle_beacon");

	setObjVar(self, travel.VAR_TRAVEL_POINT_NAME, name);
	setObjVar(self, travel.VAR_TRAVEL_COST, 500);

	attachScript(self, "structure.municipal.starport");

	return SCRIPT_CONTINUE;
}

