/** This script spawns the imperial in the Theed Palace that one returns the
 * evidence from The Warren to
 **/

include library.create;

trigger OnInitialize()
{
	obj_id imperialOfficer = create.createNpc( "imperial_army_captain", "object/mobile/dressed_imperial_captain_m.iff", getLocation( self ) );
	setInvulnerable( imperialOfficer, true );
	attachScript( imperialOfficer, "theme_park.warren.imperial_captain" );
	setObjVar( imperialOfficer, "spawnEgg", self );
	return SCRIPT_CONTINUE;
}


