/**
 * Copyright (c) ©2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:
 * Description:
 * @author       $Author: RcT and Steve 'the man!' Jakab$
 * @version      $Revision: 0$
 */

/**
 * Include Libraries
 */
// include anyLibrary;	/** a .scriptlib file */
include library.utils;
include library.craftinglib;

inherits systems.crafting.droid.crafting_base_droid_component;

/**
 * Constants
 * @{
 */
/** The version number of this script. */
const string VERSION = "v0.00.00";

/******************************/
// example skill data - this will probably go in a derived script
/******************************/

// skill names - the player must have one of these skills to use this script
const string[] REQUIRED_SKILLS = {
	"crafting_droidengineer_novice"
};

// skill mod names - these skill mods will affect the assembly part of the crafting session if the player has them
const string[] ASSEMBLY_SKILL_MODS = {
	"droid_assembly"
};

// skill mod names - these skill mods will affect the experimentation part of the crafting session if the player has them
const string[] EXPERIMENT_SKILL_MODS = {
	"droid_experimentation"
};

/**********************
 *
 *  These values are used to determine the resource contribution to the value of item attributes
 *
 **********************/
const resource_weight[] OBJ_ASSEMBLY_ATTRIBUTE_RESOURCES = {
	new resource_weight("hitPoints", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("storage_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("personality_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("medical_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("mechanism_quality", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("bomb_level", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("stimpack_capacity", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("stimpack_speed", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("auto_repair_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("trap_bonus", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("harvest_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("struct_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("decayRate", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("cmbt_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("useModifier", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("fire_potency", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("arc_projector", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("shield_heatsink", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("pain_inducer", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("quickset_metal", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("dump_capacitors", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("sampling_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1),
		new resource_weight.weight(craftinglib.RESOURCE_HEAT_RESIST, 1),
		new resource_weight.weight(craftinglib.RESOURCE_DECAY_RESIST, 1)
		}
	)

};


/**********************
 *
 *  These values are used to determine the resource max value of item attributes
 *
 **********************/

const resource_weight[] OBJ_MAX_ATTRIBUTE_RESOURCES = {
	new resource_weight("hitPoints", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("storage_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("personality_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("medical_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("mechanism_quality", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("bomb_level", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("stimpack_capacity", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("stimpack_speed", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("auto_repair_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("trap_bonus", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("harvest_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("struct_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("decayRate", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("cmbt_module", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("useModifier", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY,      1),
		new resource_weight.weight(craftinglib.RESOURCE_CONDUCTIVITY, 1)
		}
	),
	new resource_weight("fire_potency", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("arc_projector", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("shield_heatsink", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("pain_inducer", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("quickset_metal", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("dump_capacitors", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1)
		}
	),
	new resource_weight("sampling_power", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 1),
		new resource_weight.weight(craftinglib.RESOURCE_HEAT_RESIST, 1),
		new resource_weight.weight(craftinglib.RESOURCE_DECAY_RESIST, 1)
		}
	)
};
/* @} End constants */



string[] getRequiredSkills()
{
	return REQUIRED_SKILLS;
}

string[] getAssemblySkillMods()
{
	return ASSEMBLY_SKILL_MODS;
}

string[] getExperimentSkillMods()
{
	return EXPERIMENT_SKILL_MODS;
}

resource_weight[] getResourceMaxResourceWeights()
{
	return OBJ_MAX_ATTRIBUTE_RESOURCES;
}

resource_weight[] getAssemblyResourceWeights()
{
	return OBJ_ASSEMBLY_ATTRIBUTE_RESOURCES;
}

