include library.groundquests;
include library.chat;
include library.attrib;
include library.utils;

const string STF									= "ep3/sidequests";
const string_id CONTACT								= new string_id(STF, "outcast");

trigger OnAttach ()
{
	setBarkAttributes(self);
	setInvulnerable(self, true);
	attachScript(self, "conversation.ep3_forest_outcast_informant");
	return SCRIPT_CONTINUE;
}
trigger OnInitialize()
{
	setBarkAttributes(self);
	setInvulnerable(self, true);
	attachScript(self, "conversation.ep3_forest_outcast_informant");
	return SCRIPT_CONTINUE;
}

void setBarkAttributes(obj_id self)
{
	createTriggerVolume( "chat_range", 10, true );
	setAttributeInterested( self, attrib.ALL );
	return;
}

void beginChatting(obj_id self, obj_id player)
{
	chat.chat(self, CONTACT);
	return;
}

messageHandler handleReset()
{
	utils.removeScriptVar(self, "already_chatting");
	return SCRIPT_CONTINUE;
}

trigger OnTriggerVolumeEntered( string volumeName, obj_id who )
{
	if(utils.hasScriptVar(self, "already_chatting"))
	{
		return SCRIPT_CONTINUE;
	}

	if (volumeName == "chat_range")
	{
		if (groundquests.isTaskActive(who, "ep3_forest_wirartu_epic_2", 0) || groundquests.hasCompletedQuest(who, "ep3_forest_wirartu_epic_2"))
		{
			beginChatting(self, who);
			utils.setScriptVar(self, "already_chatting", 1);
			messageTo(self, "handleReset", null, 60f, false);
		}
	}
	return SCRIPT_CONTINUE;
}