/***** INCLUDES ********************************************************/
include library.buff;
include library.collection;
include library.colors;
include library.create;
include library.factions;
include library.groundquests;
include library.holiday;
include library.money;
include library.pclib;
include library.pet_lib;
include library.prose;
include library.static_item;
include library.stealth;
include library.sui;
include library.trial;
include library.utils;

/***** CONSTANTS *******************************************************/

const string QUEST_NAME				= "u16_nym_themepark_weed_pulling_ver2";
const string GENERAL_QUEST_TASK			= "fulfillRequisition";

const string TASK_WEED_TYPE_1			= "lowGrowingWeeds";
const string TASK_WEED_TYPE_2			= "tallStalkWeed";
const string TASK_WEED_TYPE_3			= "paddleCactiWeed";
const string TASK_WEED_TYPE_4			= "yellowPodWeed";
const string TASK_WEED_TYPE_5			= "floweringCactiWeed";
const string SIGNAL_WEED_TYPE_1			= "lowGrowingWeedsFound";
const string SIGNAL_WEED_TYPE_2			= "tallStalkWeedFound";
const string SIGNAL_WEED_TYPE_3			= "paddleCactiWeedFound";
const string SIGNAL_WEED_TYPE_4			= "yellowPodWeedFound";
const string SIGNAL_WEED_TYPE_5			= "floweringCactiWeedFound";

const string THEMEPARK				= "theme_park_nym/messages";

const string_id SID_NOT_WHILE_MOUNTED		= new string_id(THEMEPARK, "pull_weed_not_while_mounted");
const string_id SID_ZIP_BAR			= new string_id(THEMEPARK, "weed_zip_bar");
const string_id SID_ZIP_BAR_PADDLE		= new string_id(THEMEPARK, "weed_zip_bar_paddle");
const string_id SID_ZIP_BAR_LOW			= new string_id(THEMEPARK, "weed_zip_bar_low");
const string_id SID_ZIP_BAR_FLOWER		= new string_id(THEMEPARK, "weed_zip_bar_flower");
const string_id SID_ZIP_BAR_YELLOW		= new string_id(THEMEPARK, "weed_zip_bar_yellow");
const string_id SID_ZIP_BAR_TALL		= new string_id(THEMEPARK, "weed_zip_bar_tall");
const string_id SID_DONT_NEED_WEED		= new string_id(THEMEPARK, "dont_need_weed");
const string_id SID_CHA_CHING			= new string_id(THEMEPARK, "received_credits");

const string_id SID_MNU_USE			= new string_id(THEMEPARK, "pull_weed");
const string_id SID_NOT_SURE_HOW_DESTROY	= new string_id(THEMEPARK, "weed_not_sure_what_to_do");
const string_id SID_ALRDY_COMPLETED_QUEST	= new string_id(THEMEPARK, "weed_already_completed_quest");

const int COUNTDOWN_TIMER			= 3;
const int CASH_AMOUNT				= 25;

/***** TRIGGERS ********************************************************/

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	if(!isValidId(self) || !exists(self))
		return SCRIPT_CONTINUE;

	if(isDead(player) || isIncapacitated(player))
		return SCRIPT_CONTINUE;

	if(!hasObjVar(self, "weed_type"))
		return SCRIPT_CONTINUE;

	int mnu2 = mi.addRootMenu (menu_info_types.ITEM_USE, SID_MNU_USE);
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if(!isValidId(self) || !exists(self))
		return SCRIPT_CONTINUE;

	if(item != menu_info_types.ITEM_USE)
		return SCRIPT_CONTINUE;
	
	if(!hasObjVar(self, "weed_type"))
		return SCRIPT_CONTINUE;

	if(isDead(player) || isIncapacitated(player))
		return SCRIPT_CONTINUE;

	if(pet_lib.isMounted(player))
	{
		sendSystemMessage(player, SID_NOT_WHILE_MOUNTED);
		return SCRIPT_CONTINUE;
	}
	
	if(!groundquests.isQuestActive(player, QUEST_NAME))
	{
		sendSystemMessage(player, SID_NOT_SURE_HOW_DESTROY);	
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Player: "+player+" did not have the quest "+QUEST_NAME+" needed for this collection. canister: ("+self);	
		return SCRIPT_CONTINUE;
	}

	if(!groundquests.isTaskActive(player, QUEST_NAME, GENERAL_QUEST_TASK))
	{
		sendSystemMessage(player, SID_NOT_SURE_HOW_DESTROY);	
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Player: "+player+" did not have the quest "+QUEST_NAME+" needed for this collection. canister: ("+self);	
		return SCRIPT_CONTINUE;
	}

	int weedType = getIntObjVar(self, "weed_type");
	if(weedType < 0)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Weed: "+self+" did not have a valid weed type var");	
		return SCRIPT_CONTINUE;
	}

	string_id zipBar = SID_ZIP_BAR;
	
	switch(weedType)
	{
		case 1:
			zipBar = SID_ZIP_BAR_LOW;		
			break;
		case 2:
			zipBar = SID_ZIP_BAR_TALL;		
			break;
		case 3:
			zipBar = SID_ZIP_BAR_PADDLE;		
			break;
		case 4:
			zipBar = SID_ZIP_BAR_YELLOW;		
			break;
		case 5:
			zipBar = SID_ZIP_BAR_FLOWER;		
			break;
		default:
			break;			
	}

	
	int startTime = 0;
	int range = 3;
	int flags = 0;

	flags |= sui.CD_EVENT_INCAPACITATE;
	flags |= sui.CD_EVENT_DAMAGED;

	stealth.testInvisNonCombatAction(player, self);
	int countdownSui = sui.smartCountdownTimerSUI(self, player, "quest_countdown_timer", zipBar, startTime, COUNTDOWN_TIMER, "handleObjectSwapTimer", range, flags);
	CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Player: "+player+" is destroying Nym Weed: "+self);
	
	return SCRIPT_CONTINUE;
}

/***** MESSAGE HANDLERS ************************************************/

//Handling the count down timer for dressing a tree and stomping presents.
messageHandler handleObjectSwapTimer()
{
	if(!isValidId(self) || !exists(self))
		return SCRIPT_CONTINUE;

	if(params == null || params.equals(""))
		return SCRIPT_CONTINUE;
	
 	int pid = params.getInt("id");
	obj_id player = params.getObjId("player");
	if(!isIdValid(player) || !exists(player))
		return SCRIPT_CONTINUE;

	int bp = sui.getIntButtonPressed(params);

	// Cancel button is sent when player manually closes the countdown window,
	// or when he/she moves out of range.
	if(bp == sui.BP_CANCEL)
	{
		detachScript(player, sui.COUNTDOWNTIMER_PLAYER_SCRIPT);
		CustomerServiceLog("nyms_themepark", "weed_quest_object.handleObjectSwapTimer() cancelled");

		return SCRIPT_CONTINUE;
	}
	
	else if(bp == sui.BP_REVERT)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.handleObjectSwapTimer() Player: "+player+" failed to destroy the canister because the player moved or was disrupted. Deposit: "+self);

		// Gets the reason why the timer was aborted
		int event = params.getInt("event");

		// You can handle the situation differently depending on the reason
		if(event == sui.CD_EVENT_LOCOMOTION)
		{
			sendSystemMessage(player, new string_id("quest/groundquests", "countdown_interrupted_locomotion"));
		}
		else if(event == sui.CD_EVENT_INCAPACITATE)
		{
			sendSystemMessage(player, new string_id("quest/groundquests", "countdown_interrupted_incapacitated"));
		}
		else if(event == sui.CD_EVENT_DAMAGED)
		{
			sendSystemMessage(player, new string_id("quest/groundquests", "countdown_interrupted_damaged"));
		}

		return SCRIPT_CONTINUE;
	}

	if(!hasObjVar(player, sui.COUNTDOWNTIMER_SUI_VAR))
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.handleObjectSwapTimer() no countdowntimer");
		return SCRIPT_CONTINUE;
	}
	
	int test_pid = getIntObjVar(player, sui.COUNTDOWNTIMER_SUI_VAR);

	if(pid != test_pid)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.handleObjectSwapTimer() pid != test_pid");
		return SCRIPT_CONTINUE;
	}

	forceCloseSUIPage(pid);
	detachScript(player, sui.COUNTDOWNTIMER_PLAYER_SCRIPT);
	
	if(!groundquests.isTaskActive(player, QUEST_NAME, GENERAL_QUEST_TASK))
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.handleObjectSwapTimer() Player: "+player+" did not have the quest "+QUEST_NAME+" needed for this collection. canister: ("+self);	
		return SCRIPT_CONTINUE;
	}
	
	int weedType = getIntObjVar(self, "weed_type");
	if(weedType < 0)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Weed: "+self+" did not have a valid weed type var");	
		return SCRIPT_CONTINUE;
	}

	string questTask = "";
	string questSignal = "";
	
	switch(weedType)
	{
		case 1:
			questTask = TASK_WEED_TYPE_1;		
			questSignal = SIGNAL_WEED_TYPE_1;
			break;
		case 2:
			questTask = TASK_WEED_TYPE_2;		
			questSignal = SIGNAL_WEED_TYPE_2;
			break;
		case 3:
			questTask = TASK_WEED_TYPE_3;		
			questSignal = SIGNAL_WEED_TYPE_3;
			break;
		case 4:
			questTask = TASK_WEED_TYPE_4;		
			questSignal = SIGNAL_WEED_TYPE_4;
			break;
		case 5:
			questTask = TASK_WEED_TYPE_5;		
			questSignal = SIGNAL_WEED_TYPE_5;
			break;
		default:
			break;			
	}
	
	if(questTask == null || questTask.length() <= 0)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Player: "+player+" could not attain a valid quest task off the weed object: "+self);	
		return SCRIPT_CONTINUE;
	}

	if(questSignal == null || questSignal.length() <= 0)
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.OnObjectMenuSelect() Player: "+player+" could not attain a valid quest signal off the weed object: "+self);	
		return SCRIPT_CONTINUE;
	}

	if(groundquests.isTaskActive(player, QUEST_NAME, questTask))
	{
		groundquests.sendSignal(player, questSignal); 
	}
	else
	{
		sendSystemMessage(player, SID_DONT_NEED_WEED);
		if(!utils.hasScriptVar(player, "commPlayerWeeds"))
		{
			string npc = "object/mobile/nym_themepark_ran_machado.iff";
			string sound = "sound/sys_comm_rebel_male.snd";
			prose_package pp = new prose_package();
			prose.setStringId(pp, new string_id("theme_park_nym/messages", "extra_credit_weeds"));
			commPlayers(player, npc, sound, 10f, player, pp);
			//set scriptvar so the comm only happens once
			utils.setScriptVar(player, "commPlayerWeeds", true);
		}
		money.bankTo(money.ACCT_NEW_PLAYER_QUESTS, player, CASH_AMOUNT);
		play2dNonLoopingSound(player, groundquests.MUSIC_QUEST_RECEIVED_CREDITS);
	}
	
	messageTo(self, "destroySelf", null, 0, false);
	return SCRIPT_CONTINUE;
}

//Destroying dressed tree or stomped presents.
messageHandler destroySelf()
{
	//when the object is destroyed, tell the spawner to destroy too.
	if(!hasObjVar(self, "mySpawner"))
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.destroySelf() The Weed: "+self+" did not have a parent objvar. The parent cannot be told to destroy self.");			
	}

	obj_id parent = getObjIdObjVar(self, "mySpawner");
	if(!isValidId(parent))
	{
		CustomerServiceLog("nyms_themepark", "weed_quest_object.destroySelf() The Weed: "+self+" did not have a valid parent objvar. The parent may already be destroyed.");			
	}

	messageTo(parent, "destroySelf", null, 0, false);
	destroyObject(self);
	//CUSTOMER SERVICE LOG
	return SCRIPT_CONTINUE;
}