include library.weapons;

trigger OnAttach()
{
	messageTo (self, "bldgSetup", null, 3, true);
	return SCRIPT_CONTINUE;
}

messageHandler bldgSetup ()
{

	obj_id room3 = getCellId (self, "room3");
	location chestLoc = new location (-4.5f, 0.13f, -3.23f, "tatooine", room3);
	obj_id thechest = createObject ("object/tangible/container/drum/poi_prize_box_off.iff", chestLoc);
	obj_id quester = getObjIdObjVar (self, "player");
	setOwner (thechest, quester);
	setObjVar (thechest, "owner", quester);
	obj_id sword = weapons.createWeapon("object/weapon/melee/sword/sword_rantok.iff", thechest, rand(0.75f, 1.1f));	
	attachScript (thechest, "theme_park.jabba.chest_rantok");
	return SCRIPT_CONTINUE;
}	
