

messageHandler startLandingSequence()
{
	obj_id owner = params.getObjId("owner");

	queueCommand(self, ##"prone", self, "", COMMAND_PRIORITY_FRONT);
	setPosture(self, POSTURE_PRONE);

	dictionary d = new dictionary();
	d.put("owner", owner);

	messageTo(self, "takeOff", d, 25.0f, false);

	return SCRIPT_CONTINUE;
}

messageHandler takeOff()
{
	obj_id owner = params.getObjId("owner");

	location loc = getLocation(self);

	dictionary d = new dictionary();
	d.put("owner", owner);
	
	messageTo(self, "warpPlayer", d, 5.0f, false);
	messageTo(self, "startTakeOffSequence", d, 3.0f, false);

	return SCRIPT_CONTINUE;
}

messageHandler startTakeOffSequence()
{
	queueCommand(self, ##"stand", self, "", COMMAND_PRIORITY_FRONT);
	setPosture(self, POSTURE_UPRIGHT);

	messageTo(self, "cleanUp", null, 20.0f, false);

	return SCRIPT_CONTINUE;
}

messageHandler cleanUp()
{
	destroyObject(self);

	return SCRIPT_CONTINUE;
}

messageHandler warpPlayer()
{
	obj_id owner = params.getObjId("owner");
	//unlock the collection and warp the player
	modifyCollectionSlotValue(owner, "publish_chapter7_click_activation_01", 1);	
	warpPlayer(owner, "tatooine", 3278, 5, -4821,  null, 0, 0, 0, "", false);
	setYaw(owner, 40);
	return SCRIPT_CONTINUE;
}

