include library.utils;
include library.features;

const int SWG_BASE_GAME 		= 0x00000001;
const int SWG_COLLECTORS_GAME 	= 0x00000002;

trigger OnAttach()
{
	debugSpeakMsg( self, "feature test script attached" );
	return SCRIPT_CONTINUE;
}

trigger OnSpeaking( string text )
{
	if ( text.equals( "featuretest" ) )
	{
		sendSystemMessageTestingOnly (self, "getGameFeatures(): " + getGameFeatureBits( self  ) );
		sendSystemMessageTestingOnly (self, "getSubFeatures(): " + getSubscriptionFeatureBits( self  ) );
		sendSystemMessageTestingOnly (self, "utils.checkBit( SWG_BASE_GAME ): " + utils.checkBit( getGameFeatureBits( self ), SWG_COLLECTORS_GAME ));
		sendSystemMessageTestingOnly (self, "utils.checkBit( SWG_COLLECTORS_GAME ): " + utils.checkBit( getGameFeatureBits( self ), SWG_COLLECTORS_GAME ));
		sendSystemMessageTestingOnly (self, "isCollectorEdition" + features.isCollectorEdition( self ));
	}
	return SCRIPT_CONTINUE;
}

