include library.sui;
include library.instance;
include library.trial;

const string DECREPIT_STF			= "mustafar/decrepit_droid_factory";
const string_id SID_EXIT_TRIAL			= new string_id(DECREPIT_STF, "decrepit_exit");
const string_id SID_EXIT_TRIAL_CONFIRM		= new string_id(DECREPIT_STF, "decrepit_exit_confirm");

trigger OnAttach()
{
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	mi.addRootMenu (menu_info_types.ITEM_USE, SID_EXIT_TRIAL);

	return SCRIPT_CONTINUE;
}

//----------------------------------------------------------------------

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if (item == menu_info_types.ITEM_USE)
	{
		instance.requestExitPlayer(instance.getInstanceName(trial.getTop(self)), player);
	}

	return SCRIPT_CONTINUE;
}

