include library.ai_lib;
inherits theme_park.poi.base;

trigger OnAttach()
{
	doSpawning(self);
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	doSpawning(self);
	return SCRIPT_CONTINUE;
}

void doSpawning(obj_id self)
{
	string planet = getCurrentSceneName();
	string dangerous = "datatables/herd/dangerous_creatures.iff";
			
	string[] creatureRows = dataTableGetStringColumnNoDefaults (dangerous, planet);
	string randomAnimal = creatureRows [rand (0, creatureRows.length - 1)];
	string thing = "object/creature/monster/" + randomAnimal + "_large.iff";
	obj_id monster = poiCreateObject (thing, 3, 3 );
	obj_id vic1 = poiCreateNpc ("townperson", 5, 5);
	obj_id vic2 = poiCreateNpc ("townperson", 6, 5);
	obj_id vic3 = poiCreateNpc ("townperson", 5, 6);
	
	ai_lib.setDefaultCalmBehavior( monster, ai_lib.BEHAVIOR_SENTINEL );
	ai_lib.setDefaultCalmBehavior( vic1, ai_lib.BEHAVIOR_SENTINEL );
	ai_lib.setDefaultCalmBehavior( vic2, ai_lib.BEHAVIOR_SENTINEL );
	ai_lib.setDefaultCalmBehavior( vic3, ai_lib.BEHAVIOR_SENTINEL );
	
	faceTo (monster, vic1);
	faceTo (vic1, monster);
	faceTo (vic2, monster);
	faceTo (vic3, monster);
	
	setObjVar (monster, "vic1", vic1);
	setObjVar (monster, "vic2", vic2);
	setObjVar (monster, "vic3", vic3);
	setObjVar (vic3, "leader", 1);
		
	attachScript (vic1, "theme_park.poi.general.behavior.terrified_dialog");
	attachScript (vic2, "theme_park.poi.general.behavior.terrified_dialog");
	attachScript (vic3, "theme_park.poi.general.behavior.terrified_dialog");
	attachScript (monster, "theme_park.poi.general.behavior.pounce_creature");
	
	setAnimationMood (monster, "threaten");
	return;
}	

