include ai.ai_combat;
inherits theme_park.poi.base;

trigger OnAttach ()
{
	debugSpeakMsg (self, "First POI Test Attached");
	return SCRIPT_CONTINUE;
}

trigger OnInitialize ()
{
	string objective = poiGetObjective (self);
	if ( objective == "thug")
	{
		debugSpeakMsg (self, "In Oninitialize");
		obj_id victim = poiCreateNpc (self, "townie", "townsperson", 5, 5);
		setHealth (victim, 10000);
		obj_id thug1 = poiCreateNpc ( self, "thug1", "thug", 6, 6 );
		obj_id thug2 = poiCreateNpc ( self, "thug2", "thug", 4, 4 );
		startCombat (thug1, victim);
		return SCRIPT_CONTINUE;
	}
return SCRIPT_CONTINUE;
}



