
/**
 * Copyright (c)2000-2004 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:        atat_actor.script
 */


/***** INCLUDES ********************************************************/
include library.utils;

/***** FUNCTIONS ********************************************************/

//need to capture when killed to give out the title
trigger OnDeath(obj_id killer, obj_id corpseId)
{
	//get the list of attackers, this is anyone who did damage
	obj_id[] attackerList = utils.getObjIdBatchScriptVar(self, "creditForKills.attackerList.attackers");

	//validate the list
	if(attackerList == null || attackerList.length <= 0)
	{
		return SCRIPT_CONTINUE;
	}

	//loop thru the list
	//give the title to those who are still within 200 meters
	for(int i = 0; i < attackerList.length; ++i)
	{
		if(utils.getDistance2D(self, attackerList[i]) < 200.0)
		{
			//give title
			//place holder till we move this to another branch
			if(!hasCompletedCollectionSlot(attackerList[i], "toy_recaller"))
			{
				modifyCollectionSlotValue(attackerList[i], "toy_recaller", 1);
				sendSystemMessage(attackerList[i], new string_id("spam", "you_got_april_fools_09_title"));
			}
		}
	}
	return SCRIPT_CONTINUE;

}
// END END END END END END END END END END END END END END END END END END END END END END END END END