//------------------------------------------------
// quest_nav_point.script
// Brandon Reinhart
//------------------------------------------------

//------------------------------------------------
// Includes
//------------------------------------------------

include library.space_quest;
include library.space_utils;

//------------------------------------------------
// OnInitialize
//------------------------------------------------

trigger OnInitialize()
{
	// We want to get a preloading notification.
	requestPreloadCompleteTrigger( self );

	return SCRIPT_CONTINUE;
}

//------------------------------------------------
// OnPreloadComplete
//------------------------------------------------

trigger OnPreloadComplete()
{
	// We should register with the quest_manager now.
	obj_id questManager = getNamedObject( space_quest.QUEST_MANAGER );
	if ( questManager == null )
		return SCRIPT_CONTINUE;

	dictionary outparams = new dictionary();
	outparams.put( "point", self );
	outparams.put( "type", "nav" );
	space_utils.notifyObject( questManager, "registerQuestLocation", outparams );

	return SCRIPT_CONTINUE;
}
