/**********************************************************************
 * Copyright (c)2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:        <title>
 * Description:  <description>
 * @author       $Author:$
 * @version      $Revision:$
 **********************************************************************/

include library.callable;
include library.craftinglib;
include library.pet_lib;
include library.utils;

trigger OnGetAttributes(obj_id player, string[] names, string[] attribs)
{
	int idx = utils.getValidAttributeIndex(names);
	if (idx == -1)
		return SCRIPT_CONTINUE;

	int count = getCount(self);

	if(getCount(self) > 1)
	{
		names[idx] = "charges";
		attribs[idx] = "" + count;
		idx++;
		if (idx >= names.length)
			return SCRIPT_CONTINUE;
	}

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if(item == menu_info_types.ITEM_USE)
	{
		if(isIncapacitated(player) || isDead(player))
		{
			return SCRIPT_CONTINUE;
		}
		
		obj_id pet = callable.getCallable(player, callable.CALLABLE_TYPE_COMBAT_PET);


		if(!isIdValid(pet) || !exists(pet) || !pet_lib.isDroidPet(pet))
		{
			return SCRIPT_CONTINUE;
		}
		
		pet_lib.feedPet(pet, player);
	}

	return SCRIPT_CONTINUE;
}

