include library.chat;
include library.utils;
include library.ai_lib;
include library.utils;
include library.anims;
include library.create;
include ai.ai_combat;

const string STF_FILE = "quest/hero_of_tatooine/rancher";

trigger OnAttach()
{
	detachScript(self, "ai.ai_combat");
	setInvulnerable(self, true);
	setName(self, "Roric Goldenfield (a rancher)");
	messageTo (self, "action01", null, 1f, false);
	return SCRIPT_CONTINUE;
}

trigger OnArrivedAtLocation (string name)
{
	if (name == "wifeLoc" && !hasObjVar(self, "wifeReached"))
	{		
		setObjVar(self, "wifeReached", 1);
		//messageTo (self, "action02", null, 10f, false);
		chat.chat(self, new string_id(STF_FILE, "you_okay"));
		
		obj_id building = getTopMostContainer (self);
		obj_id wife = getObjIdObjVar(building, "wife");
		chat.chat(wife, new string_id(STF_FILE, "glad_here"));
	}

	return SCRIPT_CONTINUE;
}


messageHandler action01()
{
	obj_id structure = getTopMostContainer (self);

	if(!isIdValid(structure))
		return SCRIPT_CONTINUE;

	obj_id building = getTopMostContainer (self );
	obj_id wife = getCellId (building, "livingroom");
	location here = getLocation (self);
	string planet = here.area;
	location wifeTarget = new location (-6.53f, 0.03f, -3.21f, planet, wife);
	ai_lib.aiPathTo (self, wifeTarget);
	addLocationTarget ("wifeLoc", wifeTarget, 1);
	
	return SCRIPT_CONTINUE;
}