include library.instance;

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	menu_info_data mid = mi.getMenuItemByType(menu_info_types.ITEM_USE);
	mid.setLabel(new string_id("mustafar/old_republic_facility", "exit_terminal_use"));
	mid.setServerNotify(true);

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if(item == menu_info_types.ITEM_USE)
		instance.requestExitPlayer("old_republic_facility", player);

	return SCRIPT_CONTINUE;
}
