
trigger OnAttach()
{
	messageTo(self, "startTimer", null, 1, false);
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	messageTo(self, "startTimer", null, 1, false);
	return SCRIPT_CONTINUE;
}

messageHandler startTimer()
{
	int timer = 0;
	if(!hasObjVar(self, "timer"))
		timer = 25;
	else
	{
		timer = getIntObjVar(self, "timer");
		if(timer < 0) 
		{
			timer = 25;
		}
	}	

	messageTo(self, "selfDestruct", null, (float)timer, false);
	return SCRIPT_CONTINUE;	
}

messageHandler selfDestruct()
{
	destroyObject(self);
	return SCRIPT_CONTINUE;	
}
