include library.groundquests;

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)
{
	if (!isPlayer (item))
	{
		return SCRIPT_CONTINUE;
	}			
	
	if ( groundquests.hasCompletedQuest(item, "itp_veers_02") || isGod(item) )
	{
		return SCRIPT_CONTINUE;
	}
	
	else
	{
		string_id warning = new string_id ("theme_park_imperial/warning","veers");
		sendSystemMessage (item, warning);
		return SCRIPT_OVERRIDE;
	}

}