include library.factions;
include library.space_quest;

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)
{
	if (!isPlayer (item))
	{
		return SCRIPT_CONTINUE;
	}			
	
	if ( factions.isImperial(item) || isGod(item) )
	{
		return SCRIPT_CONTINUE;
	}
		// if they have completed the Emperor's Retreat space access quest
	else if ( space_quest.hasWonQuest(item, "destroy_surpriseattack", "naboo_station_emperors_access_quest_6" ) )
	{
		return SCRIPT_CONTINUE;
	}
	else
	{
		string_id warning = new string_id ("theme_park_imperial/warning","not_imperial");
		sendSystemMessage (item, warning);
		return SCRIPT_OVERRIDE;
	}

}