messageHandler immediate_message ()
{
	string message = params.getString ("message");
	obj_id sender = params.getObjId ("sender");
	debugSpeakMsg (self, message);
	messageTo (sender, "gotImmediate", null, 0, true);
	return SCRIPT_CONTINUE;
}	

messageHandler delayed_message ()
{
	string message = params.getString ("message");
	obj_id sender = params.getObjId ("sender");
	debugSpeakMsg (self, "Despite the delay, I " + message);
	messageTo (sender, "gotDelayed", null, 0, true);
	return SCRIPT_CONTINUE;
}