include library.create;
include library.hue;

trigger OnHearSpeech (obj_id speaker, string text)
{
	if (speaker != self)
	{
		return SCRIPT_CONTINUE;
	}
	
	location here = getLocation (self);
	
	if (text == "test")
	{
		here.x = here.x + 2;
		obj_id npc1 = createObject ("object/mobile/human_male.iff", here);
		here.x = here.x + 2;
		obj_id npc2 = createObject ("object/mobile/human_male.iff", here);
		here.x = here.x + 2;
		obj_id npc3 = createObject ("object/mobile/human_female.iff", here);
		here.x = here.x + 2;
		obj_id npc4 = createObject ("object/mobile/human_female.iff", here);
		
		dressNpc(npc1, "datatables/npc_customization/clothing/all_shirts_pants.iff");
		dressNpc(npc2, "datatables/npc_customization/clothing/all_shirts_pants.iff");
		dressNpc(npc3, "datatables/npc_customization/clothing/all_shirts_pants.iff");
		dressNpc(npc4, "datatables/npc_customization/clothing/all_shirts_pants.iff");
	}
	
	if (text == "jacket")
	{
		here.x = here.x + 2;
		obj_id npc1 = createObject ("object/mobile/human_male.iff", here);
		here.x = here.x + 2;
		obj_id npc2 = createObject ("object/mobile/human_male.iff", here);
		here.x = here.x + 2;
		obj_id npc3 = createObject ("object/mobile/human_female.iff", here);
		here.x = here.x + 2;
		obj_id npc4 = createObject ("object/mobile/human_female.iff", here);
		
		dressNpc(npc1, "datatables/npc_customization/clothing/shirt_pants_jacket.iff");
		dressNpc(npc2, "datatables/npc_customization/clothing/shirt_pants_jacket.iff");
		dressNpc(npc3, "datatables/npc_customization/clothing/shirt_pants_jacket.iff");
		dressNpc(npc4, "datatables/npc_customization/clothing/shirt_pants_jacket.iff");
	}	
	
	return SCRIPT_CONTINUE;
}

void dressNpc (obj_id npc, string clothesTable)
{
	
	clothesTable = clothesTable;
	int columns = dataTableGetNumColumns (clothesTable);

	//Just in case there's a typo or some other problem, this makes sure there won't be any naked NPC's
	if (columns == 0)
	{
		clothesTable = "datatables/npc_customization/townperson_male_clothes.iff";
		columns = dataTableGetNumColumns (clothesTable);
	}

	// This while loop checks to see how many columns worth of clothes the clothesTable
	// has and loops through until a character is dressed with everything appropriate
	// (boots, pants, shirt, dress, armor, gloves, helmet, etc.) depending on the type
	int intX = 1;
	while ( intX <= columns )
	{
		string[] clothesList = dataTableGetStringColumnNoDefaults( clothesTable, intX-1);
		int clothesNum = rand(0, clothesList.length -1 );
		string clothes = clothesList[ clothesNum ];
		int columnNum = intX-1;
		if (clothes == null)
			debugServerConsoleMsg(npc, "LIBRARY.CREATE DRESSNPC ERROR: row was " + clothesNum + " and column was " + columnNum);
		else if (clothes == "")
			debugServerConsoleMsg(npc, "LIBRARY.CREATE DRESSNPC ERROR: row was " + clothesNum + " and column was " + columnNum);
		else
		{
			obj_id newClothes = createObject (clothes, npc, "");
			if ( newClothes == null )
				debugServerConsoleMsg(npc, "LIBRARY.CREATE DRESSNPC ERROR: unable to create " + clothes + " for npc " + getName(npc) + " objid: " + npc );
		}
		intX = intX + 1;
	}
	
	hue.randomizeObject (npc);
	
	
}
