include library.utils;
include library.trial;

messageHandler setRun()
{
	setMovementRun(self);
	return SCRIPT_CONTINUE;
}

messageHandler doTaunt()
{
	obj_id[] players = trial.getPlayersInDungeon(trial.getTop(self));
	utils.messagePlayer(self, players, trial.WORKING_HK47_TAUNT);
	messageTo(self, "destroySelf", null, 20, false);
	return SCRIPT_CONTINUE;
}

messageHandler destroySelf()
{
	trial.cleanupNpc(self);
	return SCRIPT_CONTINUE;
}