
/***** INCLUDES ********************************************************/

include library.space_dungeon;
include library.space_dungeon_data;
include library.utils;
include library.sui;
include library.prose;

/***** CONSTANTS *******************************************************/

const string_id SID_LAUNCH = new string_id("ep3/sidequests", "avatar_launch");
const string_id SID_EJECT = new string_id("ep3/sidequests", "avatar_eject");

/***** TRIGGERS ********************************************************/

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	mi.addRootMenu (menu_info_types.ITEM_USE, SID_LAUNCH);
	mi.addRootMenu (menu_info_types.SERVER_MENU1, SID_EJECT);

	return SCRIPT_CONTINUE;
}

//----------------------------------------------------------------------

trigger OnObjectMenuSelect(obj_id player, int item)
{
	LOG("space_dungeon", "theme_park.dungeon.avatar_platform.terminal_launch.OnObjectMenuSelect()");

	if (item == menu_info_types.ITEM_USE)
	{
		confirmLaunch(player, self);
	}
	else if (item == menu_info_types.SERVER_MENU1)
	{
		confirmEject(player, self);
	}

	return SCRIPT_CONTINUE;
}

//----------------------------------------------------------------------

void confirmEject(obj_id player, obj_id terminal)
{
	if (hasScript(player, "theme_park.dungeon.avatar_platform.player"))
	{
		LOG("space_dungeon", "theme_park.dungeon.avatar_platform.terminal_launch.confirmEject()");

		string prompt = "Really eject?";
		int pid = sui.msgbox(player, player, prompt, sui.YES_NO, "msgDungeonEjectConfirmed");
	}
	else
	{
		warpPlayer(player, "kashyyyk_main", -670, 18, -137, null, -670, 18, -137);
	}
}

//----------------------------------------------------------------------

void confirmLaunch(obj_id player, obj_id terminal)
{
	if (hasScript(player, "theme_park.dungeon.avatar_platform.player"))
	{
		LOG("space_dungeon", "theme_park.dungeon.avatar_platform.terminal_launch.confirmLaunch()");

		string prompt = "Really launch?";
		int pid = sui.msgbox(player, player, prompt, sui.YES_NO, "msgDungeonLaunchConfirmed");
	}
	else
	{
		warpPlayer(player, "kashyyyk_main", -670, 18, -137, null, -670, 18, -137);
	}
}

//----------------------------------------------------------------------

/***** COMMANDHANDLERS *************************************************/


/***** FUNCTIONS *******************************************************/

