

trigger OnInitialize()
{
	messageTo (self, "doGating", null, 19, true);
	return SCRIPT_CONTINUE;
}


messageHandler doGating ()
{
	obj_id targetRoom = getCellId (self, "entry");
	if ( isIdValid(targetRoom) )
	{
		if ( !hasScript(targetRoom, "theme_park.corellia.content.kor_vella_ryll_smuggler_block") )
		{
			attachScript (targetRoom, "theme_park.corellia.content.kor_vella_ryll_smuggler_block");
		}
	}

	return SCRIPT_CONTINUE;
}
