include library.groundquests;

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)
{
	if (!isPlayer (item))
	{
		return SCRIPT_CONTINUE;
	}

	if ( !groundquests.hasCompletedTask(item, "corellia_38_corsec_files_04", "corsec_files_04_06") )
	{
		string_id warning = new string_id ("theme_park/corellia/quest","kor_vella_ryll_smuggler");
		sendSystemMessage (item, warning);
		return SCRIPT_OVERRIDE;
	}


	return SCRIPT_CONTINUE;
}