include library.groundquests;

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)
{
	if (!isPlayer (item))
	{
		return SCRIPT_CONTINUE;
	}

	if ( groundquests.isQuestActiveOrComplete(item, "corellia_38_corsec_files_05") )
	{
		string_id warning = new string_id ("theme_park/corellia/quest","kor_vella_mayors_office");
		sendSystemMessage (item, warning);
		return SCRIPT_OVERRIDE;
	}


	return SCRIPT_CONTINUE;
}