#!/bin/bash

if ! test -d config; then
    mkdir config;
fi

aclocal && libtoolize --force && automake --force --foreign --add-missing --copy && autoconf

SUBDIRS="engine external/ours/library/archive external/ours/library/crypto external/ours/library/fileInterface external/ours/library/localization external/ours/library/unicode external/ours/library/unicodeArchive external/ours/library/localizationArchive game external/3rd/library/platform/MonAPI2"

for d in $SUBDIRS; do 
    echo "bootstrapping $d"
    pushd $d && bash bootstrap && popd
done
