const string MSGS = "dungeon/geonosian_madbio";

trigger OnAboutToReceiveItem (obj_id destinationCell, obj_id transferrer, obj_id item)
{
	if (!isPlayer (item))
	{
		return SCRIPT_CONTINUE;
	}			
	
	string objvarKey = getStringObjVar (self, "objvar_key");
	
	if (objvarKey == null || objvarKey == "")
	{
		objvarKey = "nil";
	}
	
	if (!hasObjVar (item, objvarKey))
	{
		string_id locked = new string_id (MSGS, "door_locked");
		sendSystemMessage (item, locked);
		return SCRIPT_OVERRIDE;
	}		
		
	else
	{
		return SCRIPT_CONTINUE;
	}	
}

