trigger OnIncapacitated (obj_id killer)
{
	string name = getName (self);
	
	if (name == "Acklay")
	{
		CustomerServiceLog("DUNGEON_GeonosianBunker","*Geonosian Creature Killed: " + killer + ": " + getName(killer) + " has killed the Acklay.");
	}
	
	else
	{
		CustomerServiceLog("DUNGEON_GeonosianBunker","*Geonosian Creature Killed: " + killer + ": " + getName(killer) + " has killed the Fire Breathing Spider.");	
	}
	return SCRIPT_CONTINUE;
}