/**
 * Copyright (c) ©2000-2002 Sony Online Entertainment Inc.
 * All Rights Reserved
 *
 * Title:
 * Description:
 * @author       $Author: Travis Hicks$
 * @version      $Revision: 0$
 */

/**
 * Include Libraries
 */
// include anyLibrary;	/** a .scriptlib file */
include library.utils;
include library.craftinglib;

inherits systems.crafting.chemistry.enzyme.crafting_base_enzyme_processing;

/**
 * Constants
 * @{
 */
/** The version number of this script. */
const string VERSION = "v0.00.00";

/******************************/
// example skill data - this will probably go in a derived script
/******************************/

// skill names - the player must have one of these skills to use this script
const string[] REQUIRED_SKILLS = {
	"crafting_architect_novice"
};

// skill mod names - these skill mods will affect the assembly part of the crafting session if the player has them
const string[] ASSEMBLY_SKILL_MODS = {
	"structure_assembly"
};

// skill mod names - these skill mods will affect the experimentation part of the crafting session if the player has them
const string[] EXPERIMENT_SKILL_MODS = {
	"structure_experimentation"
};

/**********************
 *
 *  These values are used to determine the resource contribution to the value of item attributes
 *
 **********************/
const resource_weight[] OBJ_ASSEMBLY_ATTRIBUTE_RESOURCES = {
	new resource_weight("enzyme_purity", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 2),
		new resource_weight.weight(craftinglib.RESOURCE_TOUGHNESS,    4)
		}
	),
	new resource_weight("enzyme_mutagen", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 4),
		new resource_weight.weight(craftinglib.RESOURCE_SHOCK_RESIST,    2)
		}
	)
};


/**********************
 *
 *  These values are used to determine the resource max value of item attributes
 *
 **********************/

const resource_weight[] OBJ_MAX_ATTRIBUTE_RESOURCES = {
	new resource_weight("enzyme_purity", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 2),
		new resource_weight.weight(craftinglib.RESOURCE_TOUGHNESS,    4)
		}
	),
	new resource_weight("enzyme_mutagen", new resource_weight.weight[] {
		new resource_weight.weight(craftinglib.RESOURCE_QUALITY, 4),
		new resource_weight.weight(craftinglib.RESOURCE_SHOCK_RESIST,    2)
		}
	)
};
/* @} End constants */



string[] getRequiredSkills()
{
	return REQUIRED_SKILLS;
}

string[] getAssemblySkillMods()
{
	return ASSEMBLY_SKILL_MODS;
}

string[] getExperimentSkillMods()
{
	return EXPERIMENT_SKILL_MODS;
}

resource_weight[] getResourceMaxResourceWeights()
{
	return OBJ_MAX_ATTRIBUTE_RESOURCES;
}

resource_weight[] getAssemblyResourceWeights()
{
	return OBJ_ASSEMBLY_ATTRIBUTE_RESOURCES;
}

