include library.utils;

trigger OnAttach()
{
	if ( getConfigSetting("GameServer", "combatUpgradeReward") == null )
		return SCRIPT_CONTINUE;

	if ( !createRewards(self) )
	{
		messageTo( self, "handleRetryRewardNextLogin", null, 1, false );
	}

	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	if ( getConfigSetting("GameServer", "combatUpgradeReward") == null )
		detachScript( self, "cureward.cureward" );

	return SCRIPT_CONTINUE;
}

boolean createRewards( obj_id self )
{
	int bornOnDate = getPlayerBirthDate( self );
	if ( bornOnDate > 1579 )
	{
		//you don't get rewards because you were born after CU conversion
		return true;
	}


	string cuRewardOption = getConfigSetting("GameServer", "combatUpgradeReward");

	obj_id reward = createObjectInInventoryAllowOverload("object/tangible/event_perk/frn_loyalty_award_plaque_silver.iff", self );
	if (!isIdValid(reward))
		return false;

	if ( cuRewardOption == "2" )
	{
		reward = createObjectInInventoryAllowOverload("object/tangible/event_perk/frn_loyalty_award_plaque_gold.iff", self );
		if (!isIdValid(reward))
			return false;
	}
	return true;
}

messageHandler handleRetryRewardNextLogin()
{
	detachScript( self, "cureward.cureward");
	return SCRIPT_CONTINUE;
}
