include library.badge;
include library.collection;

/*
Sept. 2009 - Updated exporation trigger volumes so they could give collection icons as well as badges.
*/

trigger OnInitialize()
{
	createTriggerVolume ("badge1", 10f, true);
	return SCRIPT_CONTINUE;
}	

trigger OnTriggerVolumeEntered (string volName, obj_id breecher)
{
	if (!isPlayer (breecher))
	{
		return SCRIPT_CONTINUE;
	}
	else
	{	
		if(!hasObjVar(self, "badge") && !hasObjVar(self, "icon"))
			return SCRIPT_CONTINUE;

		if(hasObjVar(self, "badge"))
		{
			int badgeNum = getIntObjVar (self, "badge");
			string badgeName = getCollectionSlotName(badgeNum);
			if ((badgeName != null) && (badgeName.length() > 0) && (!badge.hasBadge (breecher, badgeName)))
			{
				dictionary explorerBadges = new dictionary();
				explorerBadges.put( "badgeNumber", badgeNum );
				messageTo (breecher, "explorerBadge", explorerBadges, 0, false);
				return SCRIPT_CONTINUE;
			}
		}
		else
		{
			int iconNum = getIntObjVar (self, "icon");
			string slotName = getCollectionSlotName(iconNum);
			if ((slotName != null) && (slotName.length() > 0) && (!hasCompletedCollectionSlot(breecher, slotName)))
			{
				modifyCollectionSlotValue(breecher, slotName, 1);
				return SCRIPT_CONTINUE;
			}
		}
	}
	return SCRIPT_CONTINUE;
}
