include library.static_item;

/***** CONSTS **********************************************************/

const string_id MOVED_PAINTING		= new string_id("spam", "magic_painting_moved");

/***** TRIGGERS ********************************************************/

trigger OnAttach()
{
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	return SCRIPT_CONTINUE;
}

// Player is moving painting, not allowed
trigger OnAboutToBeTransferred (obj_id destContainer, obj_id transferer)
{
	if (!isGod (transferer))
	{
		string paintingName = static_item.getStaticItemName(self);
		if (paintingName.startsWith ("item_publish_gift_magic_painting_"))
		{
			sendSystemMessage (transferer, MOVED_PAINTING);
			return SCRIPT_OVERRIDE;
		}
	}
	return SCRIPT_CONTINUE;
}
