include library.hue;
include library.sui;
include library.utils;

const string_id PCOLOR = new string_id("sui", "set_primary_color");
const string_id SCOLOR = new string_id("sui", "set_secondary_color");

trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	if(!isGod(player))
		return SCRIPT_CONTINUE;
	obj_id hueObject = self;
	if (!utils.isNestedWithin(hueObject, player))
		return SCRIPT_CONTINUE;
	
	int mnuPrimaryColor = mi.addRootMenu(menu_info_types.SERVER_MENU9, PCOLOR);
	int mnuSecondaryColor = mi.addRootMenu(menu_info_types.SERVER_MENU10, SCOLOR);		
	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if(!isGod(player))
		return SCRIPT_CONTINUE;
	obj_id hueObject = self;
	if ( !utils.isNestedWithin(hueObject, player) )
		return SCRIPT_CONTINUE;
		
	if ( item == menu_info_types.SERVER_MENU9 )			
	{
		sui.colorize(hueObject, player, hueObject, hue.INDEX_1, "handlePrimaryColorize");
	}	
	if ( item == menu_info_types.SERVER_MENU10 )			
	{
		sui.colorize(hueObject, player, hueObject, hue.INDEX_2, "handleSecondaryColorize");
	}

	return SCRIPT_CONTINUE;
}

messageHandler handlePrimaryColorize()
{
	obj_id hueObject = self;		
	int idx = sui.getColorPickerIndex(params);
	int bp = sui.getIntButtonPressed(params);
	obj_id player = sui.getPlayerId(params);
	if ( bp == sui.BP_CANCEL )
	{
		return SCRIPT_CONTINUE;
	}
	if ( idx > -1 )
	{
		custom_var myVar = getCustomVarByName(hueObject, hue.INDEX_1);
		if (myVar != null && myVar.isPalColor())
		{
			palcolor_custom_var pcVar = (palcolor_custom_var)myVar;
			pcVar.setValue(idx);			
		}
	}
	return SCRIPT_CONTINUE;
}

messageHandler handleSecondaryColorize()
{
	obj_id hueObject = self;	
	int idx = sui.getColorPickerIndex(params);
	int bp = sui.getIntButtonPressed(params);
	obj_id player = sui.getPlayerId(params);
	if ( bp == sui.BP_CANCEL )
	{
		return SCRIPT_CONTINUE;
	}
	if ( idx > -1 )
	{
		custom_var myVar = getCustomVarByName(hueObject, hue.INDEX_2);
		if (myVar != null && myVar.isPalColor())
		{
			palcolor_custom_var pcVar = (palcolor_custom_var)myVar;
			pcVar.setValue(idx);
		}
	}
	return SCRIPT_CONTINUE;
}