include library.ai_lib;
include library.utils;
include library.trial;
include library.space_dungeon;
include library.combat;
include library.prose;


trigger OnAttach()
{
	trial.setHp(self, trial.HP_SHER_KARLING);
	trial.bumpSession(self);
	return SCRIPT_CONTINUE;
}

trigger OnIncapacitated(obj_id killer)
{
	messageTo(trial.getTop(self), "praetorianDied", null, 0, false);
	return SCRIPT_CONTINUE;
}

messageHandler doAttack()
{
	obj_id[] players = trial.getValidTargetsInDungeon(trial.getTop(self));
	obj_id closest = trial.getClosest(self, players);
	startCombat(self, closest);
	return SCRIPT_CONTINUE;
}

