include library.create;
include library.utils;
include library.npe;
include library.groundquests;
include library.sequencer;
include library.static_item;

trigger OnAttach()
{
	obj_id building = getTopMostContainer(self);
	utils.setScriptVar(building, "objTerminal", self);
	setInvulnerable(self, true);
	return SCRIPT_CONTINUE;
}

trigger OnInitialize()
{
	obj_id building = getTopMostContainer(self);
	utils.setScriptVar(building, "objTerminal", self);
	setInvulnerable(self, true);
	return SCRIPT_CONTINUE;
}

trigger OnDestroy()
{
	obj_id building = getTopMostContainer(self);
	messageTo(building, "terminalDestroyed", null, 0 , false);
 	return SCRIPT_CONTINUE;
}

trigger OnObjectDisabled (obj_id killer)
{
	setInvulnerable(self, true);
	messageTo( self, "destroyDisabledLair", null, 1, false );
	return SCRIPT_CONTINUE;

}

messageHandler destroyDisabledLair()
{
	location death = getLocation( self );
	playClientEffectObj(self, "clienteffect/combat_explosion_lair_large.cef", self, "");
	playClientEffectLoc(self, "clienteffect/combat_explosion_lair_large.cef", death, 0);
	destroyObject( self );
	return SCRIPT_CONTINUE;
}