//inlcudes
include library.utils;
include library.npe;
include library.groundquests;

trigger OnReceivedItem(obj_id srcContainer, obj_id transferer, obj_id item)
{
	if(isPlayer(item))
	{
		if(groundquests.isTaskActive(item, "npe_commando", "thugs"))
		{
			npe.giveGrenadePopUp(item, null);
			//string_id grenade = new string_id("npe", "pop_grenade");
			//obj_id building = getTopMostContainer(item);
			//obj_id droid = utils.getObjIdScriptVar(building, "objDroidInvis");
			//npe.commTutorialPlayer(droid, item, 10, grenade, "", "object/mobile/dressed_npe_commando.iff");
		}
	}
	return SCRIPT_CONTINUE;
}