include library.utils;
include library.attrib;

trigger OnAttach()
{
	setObjVar(self, "hanHere", false);
	setObjVar(self, "playerHere", false);

	return SCRIPT_CONTINUE;
}

messageHandler setupTriggerVolume()
{
	obj_id building = getTopMostContainer(self);

	createTriggerVolume("npeFollowHan", 10.0f, true);

	obj_id[] contents = getTriggerVolumeContents(self, "npeFollowHan");

	obj_id hanSolo = utils.getObjIdScriptVar(building, "objHanSolo");
	obj_id player = utils.getObjIdScriptVar(building, "npe.player");

	setAttributeInterested(self, attrib.ALL);

	setAttributeAttained(player, attrib.ALL);
	setAttributeAttained(hanSolo, attrib.ALL);


	for (int i = 0; i < contents.length; i++)
	{
		if (isIdValid(contents[i]) && isPlayer(contents[i]))
		{
			setObjVar(self, "playerHere", true);
			if (getBooleanObjVar(self, "playerHere") && getBooleanObjVar(self, "hanHere"))
			{

				messageTo(building, "continueMainTable", null, 0, false);
				destroyClientPath(contents[i]);
				removeTriggerVolume("npeFollowHan");
			}
		}
	}
	return SCRIPT_CONTINUE;
}

trigger OnTriggerVolumeEntered(string volumeName, obj_id player)
{
	if (volumeName.equals("npeFollowHan"))
	{
		if (hasObjVar(player, "isHanSolo"))
		{
			setObjVar(self, "hanHere", true);
			if (getBooleanObjVar(self, "playerHere") && getBooleanObjVar(self, "hanHere"))
			{
				obj_id building = getTopMostContainer(player);
				messageTo(building, "continueMainTable", null, 0, false);
				destroyClientPath(player);
				removeTriggerVolume("npeFollowHan");
			}
		}
		if (isPlayer(player))
		{
			setObjVar(self, "playerHere", true);
			if (getBooleanObjVar(self, "playerHere") && getBooleanObjVar(self, "hanHere"))
			{
				obj_id building = getTopMostContainer(player);
				messageTo(building, "continueMainTable", null, 0, false);
				destroyClientPath(player);
				removeTriggerVolume("npeFollowHan");
			}

		}



	}
	return SCRIPT_CONTINUE;
}